from __future__ import annotations

import importlib.util
import json
from pathlib import Path

SCRIPT = Path(__file__).resolve().parents[1] / "scripts" / "wikidebia_retro_tag.py"
spec = importlib.util.spec_from_file_location("wikidebia_retro_tag", SCRIPT)
mod = importlib.util.module_from_spec(spec)
assert spec and spec.loader
spec.loader.exec_module(mod)


class FakeAdapter:
    def __init__(self, revisions):
        self.revisions = {int(k): dict(v) for k, v in revisions.items()}
        self.added = []

    def assert_preflight(self, tag):
        assert tag == "translated-fr"
        return {"rights": ["changetags"], "tag": {"name": tag, "active": True, "defined": True, "source": ["manual"]}}

    def read_revisions(self, revision_ids):
        return {rid: dict(self.revisions[rid]) for rid in revision_ids if rid in self.revisions}

    def add_tag(self, revision_ids, tag):
        for rid in revision_ids:
            tags = list(self.revisions[rid].get("tags") or [])
            if tag not in tags:
                tags.append(tag)
            self.revisions[rid]["tags"] = tags
            self.added.append(rid)


def _write_project(tmp_path: Path, *, already=False, bad_summary=False):
    debate_id = "dieu_existe_t_il"
    corpus = tmp_path / "corpus" / debate_id
    corpus.mkdir(parents=True)
    manifest = {
        "debate_id": debate_id,
        "translation_status": {"en": "published"},
        "pages": [
            {"language": "fr", "page_id": "D0001", "page_type": "debate", "canonical_title": "Dieu existe-t-il ?"},
            {"language": "fr", "page_id": "A0001", "page_type": "argument", "canonical_title": "Dieu est la cause première de l'univers"},
        ],
    }
    (corpus / "manifest.json").write_text(json.dumps(manifest, ensure_ascii=False), encoding="utf-8")
    pages = [
        ("D0001", "debate", "Does God exist?", 100, "debate text", "Dieu existe-t-il ?"),
        ("A0001", "argument", "God is the first cause of the universe", 101, "argument text", "Dieu est la cause première de l'univers"),
    ]
    state = {
        "state_version": "wikidebia-published-state-1.0",
        "debate_id": debate_id,
        "language": "en",
        "pages": [
            {"page_id": pid, "page_type": ptype, "canonical_title": title, "revision_id": revid, "content_sha256": mod.sha_text(text), "status": "published"}
            for pid, ptype, title, revid, text, _ in pages
        ],
    }
    state["state_sha256"] = mod.sha_object(state)
    state_path = tmp_path / ".state" / "published" / debate_id / "en" / "latest.json"
    state_path.parent.mkdir(parents=True)
    state_path.write_text(json.dumps(state, ensure_ascii=False), encoding="utf-8")
    revisions = {}
    for pid, ptype, title, revid, text, fr_title in pages:
        summary = mod.expected_summary(fr_title)
        if bad_summary and revid == 101:
            summary = "Content generated by ChatGPT 5.6"
        revisions[revid] = {
            "revision_id": revid,
            "parent_id": 0,
            "title": title,
            "text": text,
            "summary": summary,
            "tags": ["chatgpt"] + (["translated-fr"] if already else []),
            "user": "ChatGPT@import",
            "timestamp": "2026-08-09T19:00:00Z",
        }
    return debate_id, revisions


def test_build_and_execute_retro_tag_plan(tmp_path):
    debate_id, revisions = _write_project(tmp_path)
    adapter = FakeAdapter(revisions)
    plan = mod.build_plan(project_root=tmp_path, debate_id=debate_id, adapter=adapter, expected_user="ChatGPT@import")
    assert plan["counts"] == {"add": 2, "skip": 0, "block": 0}
    receipt = mod.execute_plan(project_root=tmp_path, plan=plan, adapter=adapter)
    assert receipt["counts"] == {"added": 2, "already_tagged": 0, "verified": 2}
    assert adapter.added == [100, 101]
    assert all("translated-fr" in adapter.revisions[rid]["tags"] for rid in (100, 101))


def test_retro_tag_is_idempotent(tmp_path):
    debate_id, revisions = _write_project(tmp_path, already=True)
    adapter = FakeAdapter(revisions)
    plan = mod.build_plan(project_root=tmp_path, debate_id=debate_id, adapter=adapter, expected_user="ChatGPT@import")
    assert plan["counts"] == {"add": 0, "skip": 2, "block": 0}


def test_retro_tag_blocks_wrong_translation_summary(tmp_path):
    debate_id, revisions = _write_project(tmp_path, bad_summary=True)
    adapter = FakeAdapter(revisions)
    plan = mod.build_plan(project_root=tmp_path, debate_id=debate_id, adapter=adapter, expected_user="ChatGPT@import")
    assert plan["counts"]["block"] == 1
    bad = [row for row in plan["operations"] if row["operation"] == "block"][0]
    assert "translation_summary_mismatch" in bad["reasons"]


def test_manage_exposes_retro_tag_command():
    text = (Path(__file__).resolve().parents[1] / "scripts" / "wikidebia_manage.py").read_text(encoding="utf-8")
    assert 'sub.add_parser("tag-translated-fr"' in text
    assert '"wikidebia_retro_tag.py"' in text


def test_retro_tag_postwrite_verification_retries_on_replica_lag(tmp_path, monkeypatch):
    debate_id, revisions = _write_project(tmp_path)

    class LaggingAdapter(FakeAdapter):
        def __init__(self, revisions):
            super().__init__(revisions)
            self.after_add = False
            self.post_add_reads = 0

        def add_tag(self, revision_ids, tag):
            super().add_tag(revision_ids, tag)
            self.after_add = True

        def read_revisions(self, revision_ids):
            rows = super().read_revisions(revision_ids)
            if self.after_add:
                self.post_add_reads += 1
                if self.post_add_reads < 3:
                    for row in rows.values():
                        row["tags"] = [tag for tag in (row.get("tags") or []) if tag != "translated-fr"]
            return rows

    monkeypatch.setattr(mod.time, "sleep", lambda _: None)
    adapter = LaggingAdapter(revisions)
    plan = mod.build_plan(project_root=tmp_path, debate_id=debate_id, adapter=adapter, expected_user="ChatGPT@import")
    receipt = mod.execute_plan(project_root=tmp_path, plan=plan, adapter=adapter)
    assert receipt["counts"]["verified"] == 2
    assert adapter.post_add_reads == 3
