from __future__ import annotations

import argparse
import datetime as dt
import difflib
import hashlib
import importlib.util
import json
import os
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable

# Import the publication adapter without requiring installation as a package.
_PUBLISH_PATH = Path(__file__).resolve().with_name("wikidebia_publish.py")
_spec = importlib.util.spec_from_file_location("wikidebia_publish_runtime", _PUBLISH_PATH)
_publish = importlib.util.module_from_spec(_spec)
assert _spec and _spec.loader
sys.modules.setdefault(_spec.name, _publish)
_spec.loader.exec_module(_publish)

PywikibotAdapter = _publish.PywikibotAdapter
normalize_wikicode = _publish.normalize_wikicode
sha_text = _publish.sha_text
sha_file = _publish.sha_file
sha_object = _publish.sha_object

KIT_VERSION = "2.2.0"
REQUIRED_VALIDATOR_VERSION = "0.4.17"
PLAN_VERSION = "wikidebia-remote-update-plan-1.0"
STATE_VERSION = "wikidebia-published-state-1.0"
RECEIPT_VERSION = "wikidebia-remote-update-receipt-1.0"
OPERATIONS = ("create", "update", "move", "redirect", "delete", "skip", "manual_review", "blocked")
GENERATED_MARKERS = (
    "avertissements-argument=Argument généré par IA",
    "avertissements-débat=Débat généré par IA",
    "argument-warnings=Argument generated by AI",
    "debate-warnings=Debate generated by AI",
    "avertissements-argument=Généré par ChatGPT",
    "avertissements-débat=Généré par ChatGPT",
)


class UpdateError(RuntimeError):
    pass


class PlanConflict(UpdateError):
    pass


class PermissionDenied(UpdateError):
    pass


def utc_now() -> str:
    return dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def load_json(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise UpdateError(f"JSON illisible : {path}") from exc
    if not isinstance(value, dict):
        raise UpdateError(f"Objet JSON attendu : {path}")
    return value


def write_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8", newline="\n")


def portable(path: Path, root: Path) -> str:
    try:
        return path.resolve().relative_to(root.resolve()).as_posix()
    except ValueError:
        return path.name


def content_version(manifest: dict[str, Any]) -> str:
    for dotted in (
        ("release", "version"),
        ("release_version",),
        ("version",),
        ("generated_date",),
    ):
        current: Any = manifest
        for key in dotted:
            if not isinstance(current, dict) or key not in current:
                current = None
                break
            current = current[key]
        if isinstance(current, str) and current.strip():
            return current.strip()
    return "manifest-" + sha_object(manifest)[:16]


def page_key(language: str, page_id: str) -> tuple[str, str]:
    return language, page_id


def is_generated(text: str, extra_markers: Iterable[str] = ()) -> bool:
    markers = tuple(GENERATED_MARKERS) + tuple(extra_markers)
    return any(marker in text for marker in markers)


def is_redirect(text: str) -> bool:
    return bool(re.match(r"^\s*#(?:REDIRECTION|REDIRECT)\s*\[\[", text, flags=re.I))


def redirect_text(language: str, target: str) -> str:
    keyword = "REDIRECTION" if language == "fr" else "REDIRECT"
    return f"#{keyword} [[{target}]]\n"


def unified_diff(old: str | None, remote: str, new: str | None) -> dict[str, str]:
    result: dict[str, str] = {}
    if old is not None:
        result["published_to_remote"] = "".join(
            difflib.unified_diff(
                normalize_wikicode(old).splitlines(keepends=True),
                normalize_wikicode(remote).splitlines(keepends=True),
                fromfile="published",
                tofile="remote",
                n=3,
            )
        )
    if new is not None:
        result["remote_to_proposed"] = "".join(
            difflib.unified_diff(
                normalize_wikicode(remote).splitlines(keepends=True),
                normalize_wikicode(new).splitlines(keepends=True),
                fromfile="remote",
                tofile="proposed",
                n=3,
            )
        )
    return result


@dataclass(frozen=True)
class StatePage:
    language: str
    page_id: str
    page_type: str
    title: str
    content_sha256: str
    revision_id: int | None
    status: str = "published"
    source_path: str | None = None
    content: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return {
            "language": self.language,
            "page_id": self.page_id,
            "page_type": self.page_type,
            "canonical_title": self.title,
            "content_sha256": self.content_sha256,
            "revision_id": self.revision_id,
            "status": self.status,
            "source_path": self.source_path,
        }


class StateResolver:
    """Resolve the last attested published state without trusting the new manifest alone."""

    def __init__(self, project_root: Path, debate_id: str, corpus_root: Path) -> None:
        self.project_root = project_root.resolve()
        self.debate_id = debate_id
        self.corpus_root = corpus_root.resolve()

    def resolve(self, languages: Iterable[str]) -> tuple[dict[tuple[str, str], StatePage], dict[str, Any]]:
        wanted = set(languages)
        explicit = self._latest_state_files(wanted)
        if explicit is not None:
            return explicit, {"kind": "published_state_receipt", "paths": sorted({p.source_path for p in explicit.values() if p.source_path})}
        previous = self._previous_manifest_state(wanted)
        if previous:
            return previous, {"kind": "previous_installed_manifest", "manifest": self._last_manifest_path}
        inventory = self._remote_inventory_state(wanted)
        if inventory is not None:
            return inventory, {"kind": "remote_inventory", "paths": sorted({p.source_path for p in inventory.values() if p.source_path})}
        raise UpdateError(
            "Dernier état publié introuvable. Un reçu d’état, un ancien manifeste installé "
            "ou un inventaire distant explicitement rattaché au débat est requis."
        )

    def _latest_state_files(self, languages: set[str]) -> dict[tuple[str, str], StatePage] | None:
        result: dict[tuple[str, str], StatePage] = {}
        base = self.project_root / ".state" / "published" / self.debate_id
        for language in sorted(languages):
            path = base / language / "latest.json"
            if not path.is_file():
                return None
            data = load_json(path)
            unsigned = dict(data)
            claimed = unsigned.pop("state_sha256", None)
            if claimed != sha_object(unsigned):
                raise UpdateError(f"Empreinte d’état publié divergente : {path}")
            if data.get("debate_id") != self.debate_id or data.get("language") != language:
                raise UpdateError(f"État publié rattaché à un autre débat ou une autre langue : {path}")
            for row in data.get("pages") or []:
                page = StatePage(
                    language=language,
                    page_id=str(row["page_id"]),
                    page_type=str(row.get("page_type") or "unknown"),
                    title=str(row["canonical_title"]),
                    content_sha256=str(row["content_sha256"]),
                    revision_id=int(row["revision_id"]) if row.get("revision_id") is not None else None,
                    status=str(row.get("status") or "published"),
                    source_path=portable(path, self.project_root),
                    content=None,
                )
                result[page_key(language, page.page_id)] = page
        return result

    def _remote_inventory_state(self, languages: set[str]) -> dict[tuple[str, str], StatePage] | None:
        """Load a signed read-only inventory explicitly attached to this debate.

        The inventory is produced outside the validator from a constrained remote scan and
        stored under .state/inventories/<debate_id>/<language>.json. It uses the same signed
        page shape as a published state and is never inferred from all wiki pages.
        """
        result: dict[tuple[str, str], StatePage] = {}
        base = self.project_root / ".state" / "inventories" / self.debate_id
        for language in sorted(languages):
            path = base / f"{language}.json"
            if not path.is_file():
                return None
            data = load_json(path)
            unsigned = dict(data)
            claimed = unsigned.pop("inventory_sha256", None)
            if claimed != sha_object(unsigned):
                raise UpdateError(f"Empreinte d’inventaire distant divergente : {path}")
            if data.get("debate_id") != self.debate_id or data.get("language") != language:
                raise UpdateError(f"Inventaire distant rattaché à un autre débat ou une autre langue : {path}")
            if data.get("inventory_mode") != "explicit_debate_pages_read_only":
                raise UpdateError(f"Inventaire distant non borné au débat : {path}")
            for row in data.get("pages") or []:
                page = StatePage(
                    language=language,
                    page_id=str(row["page_id"]),
                    page_type=str(row.get("page_type") or "unknown"),
                    title=str(row["canonical_title"]),
                    content_sha256=str(row["content_sha256"]),
                    revision_id=int(row["revision_id"]) if row.get("revision_id") is not None else None,
                    status=str(row.get("status") or "published"),
                    source_path=portable(path, self.project_root),
                    content=row.get("content") if isinstance(row.get("content"), str) else None,
                )
                result[page_key(language, page.page_id)] = page
        return result

    def _previous_manifest_state(self, languages: set[str]) -> dict[tuple[str, str], StatePage]:
        candidates: list[Path] = []
        archive_root = self.project_root / "archives" / "debates"
        if archive_root.is_dir():
            candidates.extend(
                sorted(
                    archive_root.glob(f"*-{self.debate_id}/previous-corpus/manifest.json"),
                    reverse=True,
                )
            )
        # A user may keep an explicitly named previous corpus beside the installed corpus.
        candidates.extend(sorted(self.project_root.glob(f"corpus/{self.debate_id}.previous*/manifest.json"), reverse=True))
        current_manifest = self.corpus_root / "manifest.json"
        current_sha = sha_file(current_manifest) if current_manifest.is_file() else None
        for manifest_path in candidates:
            if current_sha and sha_file(manifest_path) == current_sha:
                continue
            manifest = load_json(manifest_path)
            if manifest.get("debate_id") != self.debate_id:
                continue
            pages: dict[tuple[str, str], StatePage] = {}
            root = manifest_path.parent
            for row in manifest.get("pages") or []:
                language = str(row.get("language") or "")
                if language not in languages:
                    continue
                rel = str(row.get("file_path") or row.get("source_path") or "")
                source = root / rel if rel else None
                text = source.read_text(encoding="utf-8") if source and source.is_file() else None
                digest = str(row.get("sha256") or (sha_text(text) if text is not None else ""))
                if not digest:
                    continue
                page = StatePage(
                    language=language,
                    page_id=str(row.get("page_id")),
                    page_type=str(row.get("page_type") or "unknown"),
                    title=str(row.get("canonical_title")),
                    content_sha256=digest,
                    revision_id=None,
                    source_path=portable(source, self.project_root) if source else portable(manifest_path, self.project_root),
                    content=text,
                )
                pages[page_key(language, page.page_id)] = page
            if pages:
                self._last_manifest_path = portable(manifest_path, self.project_root)
                return pages
        return {}


class UpdateAdapter:
    """Thin extension contract around the publication adapter."""

    def __init__(self, base: Any) -> None:
        self.base = base

    def __getattr__(self, name: str) -> Any:
        return getattr(self.base, name)

    def user_rights(self) -> set[str]:
        site = getattr(self.base, "site", None)
        if site is None:
            raise UpdateError("Site non ouvert")
        data = site.simple_request(action="query", meta="userinfo", uiprop="rights").submit()
        return set(((data.get("query") or {}).get("userinfo") or {}).get("rights") or [])

    def move_page(self, *, old_title: str, new_title: str, reason: str, expected_user: str, leave_redirect: bool) -> int | None:
        site = getattr(self.base, "site", None)
        if site is None:
            raise UpdateError("Site non ouvert")
        self.base.assert_identity(expected_user)
        params: dict[str, Any] = {
            "action": "move",
            "from": old_title,
            "to": new_title,
            "reason": reason,
            "movetalk": 1,
            "assert": "user",
            "assertuser": expected_user,
            "token": site.tokens["csrf"],
        }
        if not leave_redirect:
            params["noredirect"] = 1
        data = site.simple_request(**params).submit()
        moved = data.get("move") or {}
        return int(moved["toid"]) if moved.get("toid") is not None else None

    def delete_page(self, *, title: str, reason: str, expected_user: str) -> None:
        site = getattr(self.base, "site", None)
        if site is None:
            raise UpdateError("Site non ouvert")
        self.base.assert_identity(expected_user)
        site.simple_request(**{
            "action": "delete",
            "title": title,
            "reason": reason,
            "assert": "user",
            "assertuser": expected_user,
            "token": site.tokens["csrf"],
        }).submit()

    def backlinks(self, title: str) -> list[str]:
        site = getattr(self.base, "site", None)
        if site is None:
            raise UpdateError("Site non ouvert")
        found: list[str] = []
        continuation: dict[str, Any] = {}
        while True:
            data = site.simple_request(
                action="query", list="backlinks", bltitle=title, bllimit="max", blnamespace="0", **continuation
            ).submit()
            found.extend(str(row.get("title")) for row in ((data.get("query") or {}).get("backlinks") or []) if row.get("title"))
            if not data.get("continue"):
                break
            continuation = data["continue"]
        return found


class RemoteUpdatePlanner:
    def __init__(self, config: dict[str, Any], adapter: Any, config_path: Path) -> None:
        self.config = config
        self.config_path = config_path.resolve()
        self.project_root = Path(config.get("project_root") or Path.cwd()).resolve()
        self.corpus_root = self._resolve(config["corpus_root"])
        self.manifest_path = self.corpus_root / str(config.get("manifest_file") or "manifest.json")
        self.manifest = load_json(self.manifest_path)
        self.debate_id = str(config["debate_id"])
        self.languages = tuple(config.get("languages") or ("fr", "en"))
        self.adapter = adapter if hasattr(adapter, "user_rights") else UpdateAdapter(adapter)
        self.extra_markers = tuple(config.get("generated_markers") or ())
        self.migrations = self._load_migrations()
        self._validate_config()
        self.state, self.state_source = StateResolver(self.project_root, self.debate_id, self.corpus_root).resolve(self.languages)
        self.new_pages = self._new_pages()

    def _resolve(self, value: str | Path) -> Path:
        path = Path(value).expanduser()
        return path.resolve() if path.is_absolute() else (self.project_root / path).resolve()

    def _validate_config(self) -> None:
        if self.config.get("kit_version") != KIT_VERSION:
            raise UpdateError(f"kit_version doit être {KIT_VERSION}")
        if self.manifest.get("debate_id") != self.debate_id:
            raise UpdateError("debate_id divergent entre la configuration et le manifeste")
        validator = self.config.get("validator") or {}
        if validator.get("required_version") != REQUIRED_VALIDATOR_VERSION:
            raise UpdateError(f"Le validateur requis doit être {REQUIRED_VALIDATOR_VERSION}")
        if not self.languages:
            raise UpdateError("Aucune langue sélectionnée")

    def _load_migrations(self) -> list[dict[str, Any]]:
        rel = self.config.get("migrations_file")
        if not rel:
            candidate = self.corpus_root / "data" / "remote_migrations.json"
            if not candidate.is_file():
                return []
            path = candidate
        else:
            path = self._resolve(rel)
        data = load_json(path)
        if data.get("debate_id") != self.debate_id:
            raise UpdateError("Le registre de migrations appartient à un autre débat")
        entries = data.get("entries") or []
        if not isinstance(entries, list):
            raise UpdateError("entries doit être une liste dans le registre de migrations")
        return [dict(row) for row in entries]

    def _new_pages(self) -> dict[tuple[str, str], dict[str, Any]]:
        result: dict[tuple[str, str], dict[str, Any]] = {}
        for row in self.manifest.get("pages") or []:
            language = str(row.get("language") or "")
            if language not in self.languages:
                continue
            pid = str(row.get("page_id") or "")
            if not pid:
                raise UpdateError("page_id absent dans le nouveau manifeste")
            key = page_key(language, pid)
            if key in result:
                raise UpdateError(f"Page dupliquée : {language}/{pid}")
            source = self.corpus_root / str(row.get("file_path") or row.get("source_path") or "")
            if not source.is_file():
                raise UpdateError(f"Fichier de page absent : {source}")
            text = source.read_text(encoding="utf-8")
            result[key] = {
                "language": language,
                "page_id": pid,
                "page_type": str(row.get("page_type") or "unknown"),
                "title": str(row.get("canonical_title") or ""),
                "source_path": portable(source, self.project_root),
                "content": text,
                "content_sha256": sha_text(text),
                "file_sha256": sha_file(source),
            }
        if not result:
            raise UpdateError("Le nouveau manifeste ne contient aucune page sélectionnée")
        return result

    def _site(self, language: str) -> tuple[str, str]:
        row = (self.config.get("sites") or {}).get(language) or {}
        return str(row.get("code") or language), str(row.get("expected_user") or "")

    def _validate_new_corpus(self) -> dict[str, Any]:
        validator = self.config.get("validator") or {}
        command = [str(item) for item in validator.get("command") or []]
        if not command:
            raise UpdateError("Commande du validateur absente")
        if "validate" in command:
            idx = command.index("validate")
            command = command[: idx + 1] + [str(self.corpus_root)] + command[idx + 1 :]
        else:
            command.append(str(self.corpus_root))
        for scope in validator.get("scopes") or []:
            command.extend(["--scope", str(scope)])
        command.extend(["--format", "json"])
        import subprocess
        completed = subprocess.run(command, cwd=self.project_root, text=True, capture_output=True, check=False)
        if completed.returncode != 0:
            raise UpdateError("Validation du nouveau corpus refusée :\n" + completed.stdout + completed.stderr)
        try:
            report = json.loads(completed.stdout)
        except json.JSONDecodeError as exc:
            raise UpdateError("Sortie JSON du validateur illisible") from exc
        if report.get("result") not in {"passed", "passed_with_warnings"} or int((report.get("summary") or {}).get("errors", 0)):
            raise UpdateError("Le validateur n’a pas produit un résultat positif")
        actual = str(report.get("validator_version") or report.get("version") or "")
        if not actual:
            # Recursively find the first version field, as historical reports vary.
            def find(value: Any) -> str | None:
                if isinstance(value, dict):
                    for key in ("validator_version", "version"):
                        if isinstance(value.get(key), str):
                            return value[key]
                    for child in value.values():
                        found = find(child)
                        if found:
                            return found
                if isinstance(value, list):
                    for child in value:
                        found = find(child)
                        if found:
                            return found
                return None
            actual = str(find(report) or "")
        if actual != REQUIRED_VALIDATOR_VERSION:
            raise UpdateError(f"Version réelle du validateur divergente : {actual!r}")
        return report

    def _known_other_owner(self, language: str, title: str) -> str | None:
        base = self.project_root / ".state" / "published"
        if not base.is_dir():
            return None
        for state_path in base.glob("*/*/latest.json"):
            try:
                data = load_json(state_path)
            except UpdateError:
                continue
            owner = str(data.get("debate_id") or "")
            if not owner or owner == self.debate_id or data.get("language") != language:
                continue
            for row in data.get("pages") or []:
                if row.get("status") == "published" and row.get("canonical_title") == title:
                    return owner
        return None

    def _migration_for(self, language: str, old_page_id: str) -> dict[str, Any] | None:
        matches = [
            row for row in self.migrations
            if row.get("language") == language and str(row.get("old_page_id")) == old_page_id
        ]
        if len(matches) > 1:
            raise UpdateError(f"Migration dupliquée : {language}/{old_page_id}")
        return matches[0] if matches else None

    def build_plan(self, *, mode: str = "all") -> dict[str, Any]:
        report = self._validate_new_corpus()
        buckets: dict[str, list[dict[str, Any]]] = {name: [] for name in OPERATIONS}
        comparisons: list[dict[str, Any]] = []
        for language in self.languages:
            _, user = self._site(language)
            if not user:
                raise UpdateError(f"expected_user absent pour {language}")
            self.adapter.open_language(language, user)
            try:
                self.adapter.assert_identity(user)
                self._plan_language(language, buckets, comparisons)
            finally:
                self.adapter.close_language()
        for name in OPERATIONS:
            buckets[name].sort(key=lambda row: (row.get("language", ""), row.get("phase", 99), row.get("page_type", ""), row.get("page_id", ""), row.get("title", "")))
        plan: dict[str, Any] = {
            "plan_version": PLAN_VERSION,
            "kit_version": KIT_VERSION,
            "required_validator_version": REQUIRED_VALIDATOR_VERSION,
            "debate_id": self.debate_id,
            "corpus_version": content_version(self.manifest),
            "languages": list(self.languages),
            "scope_mode": mode,
            "state_source": self.state_source,
            "new_manifest_sha256": sha_file(self.manifest_path),
            "validator_report_sha256": sha_object(report),
            "config_sha256": sha_file(self.config_path),
            "operations": buckets,
            "comparisons": comparisons,
            "counts": {name: len(buckets[name]) for name in OPERATIONS},
            "preconditions": [
                "new_corpus_validated",
                "plan_sha256_confirmed",
                "effective_rights_checked_before_first_write",
                "remote_revision_rechecked_before_each_mutation",
            ],
        }
        plan["plan_sha256"] = sha_object(plan)
        return plan

    def _base_operation(self, *, language: str, page_id: str, page_type: str, title: str, justification: str) -> dict[str, Any]:
        return {
            "wiki": str((self.config.get("sites") or {}).get(language, {}).get("code") or language),
            "language": language,
            "title": title,
            "page_id": page_id,
            "page_type": page_type,
            "old_sha256": None,
            "new_sha256": None,
            "expected_revision_id": None,
            "observed_revision_id": None,
            "justification": justification,
            "preconditions": [],
            "result": None,
            "phase": 99,
        }

    def _plan_language(self, language: str, buckets: dict[str, list[dict[str, Any]]], comparisons: list[dict[str, Any]]) -> None:
        old = {key: value for key, value in self.state.items() if key[0] == language}
        new = {key: value for key, value in self.new_pages.items() if key[0] == language}
        handled_old: set[tuple[str, str]] = set()

        # Current corpus pages: create, skip, controlled update, move, or review.
        for key, proposed in new.items():
            prior = old.get(key)
            if prior and prior.title != proposed["title"]:
                self._plan_move(prior, proposed, buckets, comparisons)
                handled_old.add(key)
                continue
            exists, revision_id, remote_text = self.adapter.read_page(proposed["title"])
            op = self._base_operation(
                language=language,
                page_id=proposed["page_id"],
                page_type=proposed["page_type"],
                title=proposed["title"],
                justification="Page du nouveau corpus",
            )
            op.update({
                "source_path": proposed["source_path"],
                "local_file_sha256": proposed["file_sha256"],
                "new_sha256": proposed["content_sha256"],
                "observed_revision_id": revision_id,
                "remote_sha256": sha_text(remote_text) if exists else None,
                "phase": 1 if proposed["page_type"] == "debate" else 2,
            })
            if not exists:
                op["preconditions"] = ["title_absent_at_execution"]
                buckets["create"].append(op)
            elif sha_text(remote_text) == proposed["content_sha256"]:
                op["justification"] = "Contenu distant déjà équivalent"
                op["phase"] = 0
                buckets["skip"].append(op)
            elif prior is None:
                op["justification"] = "Page existante non attestée dans l’ancien état publié"
                op["phase"] = 0
                op["remote_excerpt"] = remote_text[:500]
                buckets["blocked"].append(op)
            elif self._remote_matches_prior(prior, revision_id, remote_text):
                op.update({
                    "old_sha256": prior.content_sha256,
                    "expected_revision_id": revision_id,
                    "justification": "Page inchangée depuis la dernière publication automatisée; remplacement contrôlé autorisé",
                    "preconditions": ["same_debate_id", "remote_matches_published_state", "baserevid_unchanged"],
                    "phase": 1 if proposed["page_type"] == "debate" else 3,
                })
                buckets["update"].append(op)
            else:
                op.update({
                    "old_sha256": prior.content_sha256,
                    "expected_revision_id": prior.revision_id,
                    "justification": "Modification humaine ou provenance distante indéterminée détectée",
                    "phase": 0,
                })
                comparison = self._comparison(prior, remote_text, proposed["content"])
                comparisons.append(comparison)
                op["comparison_id"] = comparison["comparison_id"]
                buckets["manual_review"].append(op)

        # Retired pages: explicit merge policy or safe deletion; never infer ownership from absence alone.
        for key, prior in old.items():
            if key in handled_old or key in new:
                continue
            migration = self._migration_for(language, prior.page_id)
            if migration and migration.get("kind") == "merge":
                self._plan_merge(prior, migration, buckets, comparisons)
            else:
                self._plan_retirement(prior, migration, buckets, comparisons)

    def _remote_matches_prior(self, prior: StatePage, revision_id: int | None, remote_text: str) -> bool:
        digest_matches = sha_text(remote_text) == prior.content_sha256
        revision_matches = prior.revision_id is not None and revision_id == prior.revision_id
        return digest_matches or revision_matches

    def _comparison(self, prior: StatePage, remote_text: str, proposed_text: str | None) -> dict[str, Any]:
        payload = {
            "language": prior.language,
            "page_id": prior.page_id,
            "title": prior.title,
            "published_sha256": prior.content_sha256,
            "remote_sha256": sha_text(remote_text),
            "proposed_sha256": sha_text(proposed_text) if proposed_text is not None else None,
            "diffs": unified_diff(prior.content, remote_text, proposed_text),
        }
        payload["comparison_id"] = sha_object(payload)[:20]
        return payload

    def _plan_move(self, prior: StatePage, proposed: dict[str, Any], buckets: dict[str, list[dict[str, Any]]], comparisons: list[dict[str, Any]]) -> None:
        source_exists, source_rev, source_text = self.adapter.read_page(prior.title)
        target_exists, target_rev, target_text = self.adapter.read_page(proposed["title"])
        op = self._base_operation(
            language=prior.language,
            page_id=prior.page_id,
            page_type=prior.page_type,
            title=prior.title,
            justification="Titre canonique modifié sans changement d’identité logique",
        )
        op.update({
            "old_title": prior.title,
            "new_title": proposed["title"],
            "old_sha256": prior.content_sha256,
            "new_sha256": proposed["content_sha256"],
            "source_path": proposed["source_path"],
            "local_file_sha256": proposed["file_sha256"],
            "expected_revision_id": source_rev,
            "observed_revision_id": source_rev,
            "target_revision_id": target_rev,
            "policy": "move",
            "leave_redirect": bool(self.config.get("move_leave_redirect", True)),
            "phase": 4,
            "preconditions": ["source_matches_published_state", "target_absent", "move_right"],
        })
        if not source_exists:
            if target_exists and sha_text(target_text) == proposed["content_sha256"]:
                op["title"] = proposed["title"]
                op["justification"] = "Déplacement déjà effectué et cible équivalente"
                op["phase"] = 0
                buckets["skip"].append(op)
            else:
                op["justification"] = "Source du déplacement absente et cible non équivalente"
                op["phase"] = 0
                buckets["blocked"].append(op)
            return
        if target_exists:
            op["justification"] = "La cible du déplacement existe déjà"
            op["phase"] = 0
            buckets["blocked"].append(op)
            return
        if not self._remote_matches_prior(prior, source_rev, source_text):
            comparison = self._comparison(prior, source_text, proposed["content"])
            comparisons.append(comparison)
            op["comparison_id"] = comparison["comparison_id"]
            op["justification"] = "Source du déplacement modifiée depuis la publication automatisée"
            op["phase"] = 0
            buckets["manual_review"].append(op)
            return
        buckets["move"].append(op)

    def _plan_merge(self, prior: StatePage, migration: dict[str, Any], buckets: dict[str, list[dict[str, Any]]], comparisons: list[dict[str, Any]]) -> None:
        target_id = str(migration.get("target_page_id") or "")
        target = self.new_pages.get(page_key(prior.language, target_id))
        if not target:
            op = self._base_operation(language=prior.language, page_id=prior.page_id, page_type=prior.page_type, title=prior.title, justification="Cible de fusion absente du nouveau corpus")
            buckets["blocked"].append(op)
            return
        policy = str(migration.get("policy") or "redirect")
        if policy == "delete":
            self._plan_retirement(prior, {**migration, "reason": "fusion", "target_title": target["title"]}, buckets, comparisons)
            return
        if policy != "redirect":
            raise UpdateError(f"Politique de fusion inconnue : {policy}")
        exists, revision_id, remote_text = self.adapter.read_page(prior.title)
        op = self._base_operation(language=prior.language, page_id=prior.page_id, page_type=prior.page_type, title=prior.title, justification="Argument fusionné; redirection explicite vers la page conservée")
        desired = redirect_text(prior.language, target["title"])
        backlinks = self.adapter.backlinks(prior.title) if exists else []
        op.update({
            "old_sha256": prior.content_sha256,
            "new_sha256": sha_text(desired),
            "redirect_target": target["title"],
            "expected_revision_id": revision_id,
            "observed_revision_id": revision_id,
            "remote_sha256": sha_text(remote_text) if exists else None,
            "backlinks": backlinks,
            "phase": 5,
            "preconditions": ["same_debate_id", "source_matches_published_state", "target_in_new_corpus", "edit_right"],
        })
        if not exists:
            op["justification"] = "Ancienne page déjà absente"
            op["phase"] = 0
            buckets["skip"].append(op)
        elif sha_text(remote_text) == sha_text(desired):
            op["justification"] = "Redirection déjà installée"
            op["phase"] = 0
            buckets["skip"].append(op)
        elif not self._remote_matches_prior(prior, revision_id, remote_text):
            comparison = self._comparison(prior, remote_text, desired)
            comparisons.append(comparison)
            op["comparison_id"] = comparison["comparison_id"]
            op["justification"] = "Ancienne page fusionnée modifiée manuellement"
            op["phase"] = 0
            buckets["manual_review"].append(op)
        else:
            buckets["redirect"].append(op)

    def _plan_retirement(self, prior: StatePage, migration: dict[str, Any] | None, buckets: dict[str, list[dict[str, Any]]], comparisons: list[dict[str, Any]]) -> None:
        reason = str((migration or {}).get("reason") or (migration or {}).get("kind") or "suppression")
        target = (migration or {}).get("target_title")
        owner = self._known_other_owner(prior.language, prior.title)
        exists, revision_id, remote_text = self.adapter.read_page(prior.title)
        op = self._base_operation(language=prior.language, page_id=prior.page_id, page_type=prior.page_type, title=prior.title, justification=f"Page retirée de l’ancien corpus ({reason})")
        op.update({
            "old_sha256": prior.content_sha256,
            "expected_revision_id": prior.revision_id,
            "observed_revision_id": revision_id,
            "remote_sha256": sha_text(remote_text) if exists else None,
            "retirement_reason": reason,
            "target": target,
            "phase": 7,
            "preconditions": [
                "attested_in_previous_state",
                "absent_from_new_corpus",
                "not_owned_by_other_known_debate",
                "remote_matches_published_state",
                "generated_marker_present",
                "delete_right",
            ],
        })
        if not exists:
            op["justification"] = "Page retirée déjà absente; reprise idempotente"
            op["phase"] = 0
            buckets["skip"].append(op)
            return
        if owner:
            op["justification"] = f"Titre également utilisé par le débat {owner}"
            op["other_debate_id"] = owner
            op["phase"] = 0
            buckets["blocked"].append(op)
            return
        if is_redirect(remote_text):
            op["justification"] = "L’ancienne page est devenue une redirection ou une page indépendante"
            op["phase"] = 0
            buckets["manual_review"].append(op)
            return
        if not self._remote_matches_prior(prior, revision_id, remote_text):
            comparison = self._comparison(prior, remote_text, None)
            comparisons.append(comparison)
            op["comparison_id"] = comparison["comparison_id"]
            op["justification"] = "Page retirée modifiée après la dernière publication automatisée"
            op["phase"] = 0
            buckets["manual_review"].append(op)
            return
        if not is_generated(remote_text, self.extra_markers):
            op["justification"] = "Marqueur Wikidéb’IA attendu absent"
            op["phase"] = 0
            buckets["blocked"].append(op)
            return
        try:
            op["backlinks"] = self.adapter.backlinks(prior.title)
        except Exception:
            op["backlinks"] = []
        buckets["delete"].append(op)


class PlanExecutor:
    def __init__(self, config: dict[str, Any], adapter: Any, config_path: Path) -> None:
        self.config = config
        self.config_path = config_path.resolve()
        self.project_root = Path(config.get("project_root") or Path.cwd()).resolve()
        self.corpus_root = self._resolve(config["corpus_root"])
        self.manifest = load_json(self.corpus_root / str(config.get("manifest_file") or "manifest.json"))
        self.debate_id = str(config["debate_id"])
        self.languages = tuple(config.get("languages") or ("fr", "en"))
        self.adapter = adapter if hasattr(adapter, "user_rights") else UpdateAdapter(adapter)
        self.logs_dir = self._resolve(config.get("logs_dir") or "logs")
        self.state_dir = self._resolve(config.get("published_state_dir") or ".state/published")
        self.receipts_dir = self._resolve(config.get("receipts_dir") or ".state/receipts")

    def _resolve(self, value: str | Path) -> Path:
        path = Path(value).expanduser()
        return path.resolve() if path.is_absolute() else (self.project_root / path).resolve()

    def verify_plan(self, plan: dict[str, Any], confirmation: str) -> None:
        unsigned = dict(plan)
        claimed = unsigned.pop("plan_sha256", None)
        if not claimed or claimed != sha_object(unsigned) or confirmation != claimed:
            raise PlanConflict("Empreinte du plan divergente")
        checks = {
            "plan_version": PLAN_VERSION,
            "kit_version": KIT_VERSION,
            "required_validator_version": REQUIRED_VALIDATOR_VERSION,
            "debate_id": self.debate_id,
            "new_manifest_sha256": sha_file(self.corpus_root / "manifest.json"),
            "config_sha256": sha_file(self.config_path),
        }
        for field, expected in checks.items():
            if plan.get(field) != expected:
                raise PlanConflict(f"Plan divergent : {field}")
        if (plan.get("operations") or {}).get("blocked"):
            raise PlanConflict("Le plan contient des opérations bloquées")

    def _selected_operations(self, plan: dict[str, Any], *, only_delete: bool, no_delete: bool) -> list[dict[str, Any]]:
        operations = plan.get("operations") or {}
        names: tuple[str, ...]
        if only_delete:
            names = ("redirect", "delete")
        elif no_delete:
            names = ("create", "update", "move", "redirect")
        else:
            names = ("create", "update", "move", "redirect", "delete")
        selected: list[dict[str, Any]] = []
        for name in names:
            for row in operations.get(name) or []:
                selected.append({**row, "operation": name})
        return selected

    @staticmethod
    def _required_rights(operation: str) -> set[str]:
        return {
            "create": {"edit", "createpage"},
            "update": {"edit"},
            "move": {"move"},
            "redirect": {"edit"},
            "delete": {"delete"},
        }.get(operation, set())

    def _preflight_rights(self, selected: list[dict[str, Any]]) -> None:
        for language in self.languages:
            relevant = [row for row in selected if row["language"] == language]
            if not relevant:
                continue
            expected_user = str(self.config["sites"][language]["expected_user"])
            self.adapter.open_language(language, expected_user)
            try:
                self.adapter.assert_identity(expected_user)
                available = self.adapter.user_rights()
                required = set().union(*(self._required_rights(row["operation"]) for row in relevant))
                missing = sorted(required - available)
                if missing:
                    raise PermissionDenied(
                        f"Droits MediaWiki absents sur {language} : {', '.join(missing)}. "
                        "Aucune écriture n’a été effectuée."
                    )
            finally:
                self.adapter.close_language()

    def execute(self, plan: dict[str, Any], confirmation: str, *, only_delete: bool = False, no_delete: bool = False) -> dict[str, Any]:
        if only_delete and no_delete:
            raise UpdateError("--only-delete et --no-delete sont incompatibles")
        self.verify_plan(plan, confirmation)
        selected = self._selected_operations(plan, only_delete=only_delete, no_delete=no_delete)
        self._preflight_rights(selected)
        lock = self._acquire_lock()
        results: list[dict[str, Any]] = []
        try:
            for language in self.languages:
                rows = [row for row in selected if row["language"] == language]
                if not rows:
                    continue
                user = str(self.config["sites"][language]["expected_user"])
                self.adapter.open_language(language, user)
                try:
                    self.adapter.assert_identity(user)
                    ordered = sorted(rows, key=lambda item: (item.get("phase", 99), item.get("page_id", "")))
                    for row in [item for item in ordered if item["operation"] != "delete"]:
                        results.append(self._execute_one(row, user, plan))
                    # Verify the complete new graph before the first destructive deletion.
                    delete_rows = [item for item in ordered if item["operation"] == "delete"]
                    if delete_rows:
                        self._verify_new_pages(language)
                    for row in delete_rows:
                        results.append(self._execute_one(row, user, plan))
                finally:
                    self.adapter.close_language()
            receipt = self._final_receipt(plan, results, only_delete=only_delete, no_delete=no_delete)
            self._write_receipt(receipt)
            self._write_published_states(plan, receipt)
            return receipt
        finally:
            try:
                lock.unlink()
            except FileNotFoundError:
                pass

    def _acquire_lock(self) -> Path:
        path = self.project_root / ".state" / "locks" / f"{self.debate_id}.lock"
        path.parent.mkdir(parents=True, exist_ok=True)
        try:
            fd = os.open(path, os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o600)
        except FileExistsError as exc:
            raise UpdateError(f"Une reprise est déjà verrouillée : {path}") from exc
        with os.fdopen(fd, "w", encoding="utf-8") as stream:
            stream.write(str(os.getpid()))
        return path

    def _summary(self, language: str, operation: str, plan: dict[str, Any]) -> str:
        configured = (self.config.get("edit_summaries") or {}).get(language)
        if configured:
            return str(configured).format(debate_id=self.debate_id, corpus_version=plan.get("corpus_version"), operation=operation)
        if language == "fr":
            return f"Mise à jour du corpus Wikidéb’IA {self.debate_id}, version {plan.get('corpus_version')}"
        return f"Update of Wikidéb’IA corpus {self.debate_id}, version {plan.get('corpus_version')}"

    def _source_text(self, row: dict[str, Any]) -> str:
        path = self._resolve(row["source_path"])
        if sha_file(path) != row.get("local_file_sha256"):
            raise PlanConflict(f"Fichier local modifié depuis le plan : {row['source_path']}")
        text = path.read_text(encoding="utf-8")
        if sha_text(text) != row.get("new_sha256"):
            raise PlanConflict(f"Contenu local divergent du plan : {row['title']}")
        return text

    def _execute_one(self, row: dict[str, Any], user: str, plan: dict[str, Any]) -> dict[str, Any]:
        operation = row["operation"]
        title = row["title"]
        exists, revision_id, remote_text = self.adapter.read_page(title)
        summary = self._summary(row["language"], operation, plan)
        result = {"operation": operation, "language": row["language"], "page_id": row["page_id"], "title": title, "status": None}
        if operation == "create":
            desired = self._source_text(row)
            if exists:
                if sha_text(remote_text) == row["new_sha256"]:
                    result.update(status="already_done", revision_id=revision_id)
                    return result
                raise PlanConflict(f"Collision apparue après le plan : {title}")
            new_rev = self.adapter.write_page(title=title, text=desired, summary=summary, tags=["chatgpt"], expected_user=user, create_only=True, base_revision_id=None)
            result.update(status="created", revision_id=new_rev, content_sha256=sha_text(desired))
            return result
        if operation == "update":
            desired = self._source_text(row)
            if not exists or revision_id is None:
                raise PlanConflict(f"Page à mettre à jour devenue absente : {title}")
            if sha_text(remote_text) == row["new_sha256"]:
                result.update(status="already_done", revision_id=revision_id)
                return result
            if revision_id != row.get("expected_revision_id") or sha_text(remote_text) != row.get("old_sha256"):
                raise PlanConflict(f"Modification distante intervenue depuis le plan : {title}")
            new_rev = self.adapter.write_page(title=title, text=desired, summary=summary, tags=["chatgpt"], expected_user=user, create_only=False, base_revision_id=revision_id)
            result.update(status="updated", old_revision_id=revision_id, revision_id=new_rev, content_sha256=sha_text(desired))
            return result
        if operation == "move":
            old_title, new_title = row["old_title"], row["new_title"]
            source_exists, source_rev, source_text = self.adapter.read_page(old_title)
            target_exists, target_rev, target_text = self.adapter.read_page(new_title)
            desired = self._source_text(row)
            if not source_exists:
                if target_exists and sha_text(target_text) == row["new_sha256"]:
                    result.update(status="already_done", title=new_title, revision_id=target_rev)
                    return result
                raise PlanConflict(f"Source du déplacement absente : {old_title}")
            if target_exists:
                raise PlanConflict(f"Cible du déplacement apparue : {new_title}")
            if source_rev != row.get("expected_revision_id") or sha_text(source_text) != row.get("old_sha256"):
                raise PlanConflict(f"Source du déplacement modifiée : {old_title}")
            self.adapter.move_page(old_title=old_title, new_title=new_title, reason=summary, expected_user=user, leave_redirect=bool(row.get("leave_redirect", True)))
            moved_exists, moved_rev, moved_text = self.adapter.read_page(new_title)
            if not moved_exists or moved_rev is None:
                raise PlanConflict(f"Déplacement non vérifiable : {new_title}")
            if sha_text(moved_text) != row["new_sha256"]:
                moved_rev2 = self.adapter.write_page(title=new_title, text=desired, summary=summary, tags=["chatgpt"], expected_user=user, create_only=False, base_revision_id=moved_rev)
                moved_rev = moved_rev2
            result.update(status="moved", title=new_title, revision_id=moved_rev)
            return result
        if operation == "redirect":
            desired = redirect_text(row["language"], row["redirect_target"])
            if not exists or revision_id is None:
                result.update(status="already_absent")
                return result
            if sha_text(remote_text) == sha_text(desired):
                result.update(status="already_done", revision_id=revision_id)
                return result
            if revision_id != row.get("expected_revision_id") or sha_text(remote_text) != row.get("old_sha256"):
                raise PlanConflict(f"Page à rediriger modifiée depuis le plan : {title}")
            new_rev = self.adapter.write_page(title=title, text=desired, summary=summary, tags=["chatgpt"], expected_user=user, create_only=False, base_revision_id=revision_id)
            result.update(status="redirected", revision_id=new_rev, target=row["redirect_target"])
            return result
        if operation == "delete":
            if not exists:
                result.update(status="already_absent")
                return result
            if revision_id != row.get("observed_revision_id") or sha_text(remote_text) != row.get("old_sha256"):
                raise PlanConflict(f"Page à supprimer modifiée depuis le plan : {title}")
            if not is_generated(remote_text, self.config.get("generated_markers") or ()):
                raise PlanConflict(f"Marqueur Wikidéb’IA absent avant suppression : {title}")
            self.adapter.delete_page(title=title, reason=summary, expected_user=user)
            after_exists, _, _ = self.adapter.read_page(title)
            if after_exists:
                raise PlanConflict(f"Suppression non vérifiée : {title}")
            result.update(status="deleted", old_revision_id=revision_id)
            return result
        raise UpdateError(f"Opération inconnue : {operation}")

    def _verify_new_pages(self, language: str) -> None:
        for row in self.manifest.get("pages") or []:
            if row.get("language") != language:
                continue
            source = self.corpus_root / str(row.get("file_path") or row.get("source_path") or "")
            desired_sha = sha_text(source.read_text(encoding="utf-8"))
            exists, _, remote_text = self.adapter.read_page(str(row.get("canonical_title")))
            if not exists or sha_text(remote_text) != desired_sha:
                raise PlanConflict(
                    "Suppression finale interdite : le nouveau graphe publié n’est pas entièrement équivalent "
                    f"pour {language}/{row.get('page_id')}"
                )

    def _final_receipt(self, plan: dict[str, Any], results: list[dict[str, Any]], *, only_delete: bool, no_delete: bool) -> dict[str, Any]:
        receipt: dict[str, Any] = {
            "receipt_version": RECEIPT_VERSION,
            "kit_version": KIT_VERSION,
            "debate_id": self.debate_id,
            "corpus_version": plan.get("corpus_version"),
            "plan_sha256": plan["plan_sha256"],
            "executed_at": utc_now(),
            "execution_mode": "only_delete" if only_delete else ("no_delete" if no_delete else "full_update"),
            "results": results,
            "counts": {},
        }
        statuses = sorted({str(row.get("status")) for row in results})
        receipt["counts"] = {status: sum(1 for row in results if row.get("status") == status) for status in statuses}
        receipt["receipt_sha256"] = sha_object(receipt)
        return receipt

    def _write_receipt(self, receipt: dict[str, Any]) -> None:
        stamp = receipt["executed_at"].replace(":", "").replace("-", "")
        directory = self.receipts_dir / self.debate_id
        write_json(directory / f"{stamp}.json", receipt)
        write_json(directory / "latest.json", receipt)

    def _write_published_states(self, plan: dict[str, Any], receipt: dict[str, Any]) -> None:
        # Read the final remote state sequentially. This captures revision IDs for future safe updates.
        for language in self.languages:
            user = str(self.config["sites"][language]["expected_user"])
            self.adapter.open_language(language, user)
            try:
                pages: list[dict[str, Any]] = []
                for row in self.manifest.get("pages") or []:
                    if row.get("language") != language:
                        continue
                    title = str(row.get("canonical_title"))
                    exists, revision_id, remote_text = self.adapter.read_page(title)
                    if not exists or revision_id is None:
                        continue
                    pages.append({
                        "page_id": str(row.get("page_id")),
                        "page_type": str(row.get("page_type") or "unknown"),
                        "canonical_title": title,
                        "content_sha256": sha_text(remote_text),
                        "revision_id": revision_id,
                        "status": "published",
                    })
                state: dict[str, Any] = {
                    "state_version": STATE_VERSION,
                    "debate_id": self.debate_id,
                    "language": language,
                    "corpus_version": plan.get("corpus_version"),
                    "publication_date": utc_now(),
                    "source_manifest_sha256": sha_file(self.corpus_root / "manifest.json"),
                    "plan_sha256": plan["plan_sha256"],
                    "receipt_path": portable(self.receipts_dir / self.debate_id / "latest.json", self.project_root),
                    "receipt_sha256": receipt["receipt_sha256"],
                    "pages": sorted(pages, key=lambda row: (row["page_type"], row["page_id"])),
                }
                state["state_sha256"] = sha_object(state)
                directory = self.state_dir / self.debate_id / language
                write_json(directory / "latest.json", state)
                write_json(directory / f"{state['publication_date'].replace(':', '').replace('-', '')}.json", state)
            finally:
                self.adapter.close_language()


def build_adapter(config: dict[str, Any], project_root: Path) -> Any:
    def resolve(value: str | Path) -> Path:
        path = Path(value).expanduser()
        return path.resolve() if path.is_absolute() else (project_root / path).resolve()
    family_file = config.get("family_file")
    base = PywikibotAdapter(
        str(config.get("family") or "wikidebates"),
        {language: str(config["sites"][language]["code"]) for language in config.get("languages") or []},
        resolve(config["pywikibot_dir"]),
        resolve(family_file) if family_file else None,
    )
    return UpdateAdapter(base)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Reprise distante contrôlée d’un corpus Wikidéb’IA déjà publié")
    parser.add_argument("--config", required=True)
    parser.add_argument("--mode", choices=("plan", "execute"), default="plan")
    parser.add_argument("--plan-output", default="wikidebia_update_plan.json")
    parser.add_argument("--plan-input")
    parser.add_argument("--confirm-plan-sha256")
    parser.add_argument("--only-delete", action="store_true")
    parser.add_argument("--no-delete", action="store_true")
    args = parser.parse_args(argv)
    config_path = Path(args.config).resolve()
    config = load_json(config_path)
    project_root = Path(config.get("project_root") or Path.cwd()).resolve()
    adapter = build_adapter(config, project_root)
    if args.mode == "plan":
        planner = RemoteUpdatePlanner(config, adapter, config_path)
        mode = "only_delete" if args.only_delete else ("no_delete" if args.no_delete else "all")
        plan = planner.build_plan(mode=mode)
        write_json(Path(args.plan_output), plan)
        print(plan["plan_sha256"])
        print(json.dumps(plan["counts"], ensure_ascii=False, sort_keys=True))
        return 3 if plan["operations"]["blocked"] else 0
    if not args.plan_input or not args.confirm_plan_sha256:
        raise UpdateError("execute exige --plan-input et --confirm-plan-sha256")
    plan = load_json(Path(args.plan_input))
    executor = PlanExecutor(config, adapter, config_path)
    receipt = executor.execute(plan, args.confirm_plan_sha256, only_delete=args.only_delete, no_delete=args.no_delete)
    print(json.dumps(receipt["counts"], ensure_ascii=False, sort_keys=True))
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:  # No unhandled Pywikibot traceback in production automation.
        print(f"MISE À JOUR BLOQUÉE : {exc}", file=sys.stderr)
        raise SystemExit(2)
