from pathlib import Path

from wikidebia_validator.editorial import validate_introduction_review_data, validate_summary_style_review_data
from wikidebia_validator.package import PackageContext
from wikidebia_validator.report import Report
from wikidebia_validator.wikicode import validate_page


def _manifest(root: Path):
    (root / "manifest.json").write_text('{"normative_versions":{"consolidated_norm":"1.2.24"}}', encoding="utf-8")


def _argument(root: Path, summary: str, lang: str = "fr") -> Report:
    _manifest(root)
    page = root / "argument.wiki"
    if lang == "fr":
        text = f"""{{{{Argument
|avertissements-argument=Argument généré par IA
|résumé={summary}
|rubriques=Philosophie
|mots-clés=réalisme
|date-création=2026-08-02
}}}}
"""
    else:
        text = f"""{{{{Argument
|argument-warnings=Argument generated by AI
|summary={summary}
|sections=Philosophy
|keywords=realism
|creation-date=2026-08-02
}}}}
"""
    page.write_text(text, encoding="utf-8")
    report = Report("0.4.28", str(root), ["wikicode"])
    validate_page(PackageContext(root, report), {"page_id":"A0001","page_type":"argument","language":lang,"file_path":"argument.wiki"})
    return report


def test_french_hover_link_is_accepted(tmp_path: Path):
    report = _argument(tmp_path, "L'{{Lien Wikipédia|article=effet Ganzfeld}} désigne une condition perceptive étudiée.")
    assert not any(f.code == "WDV-MWK-020" for f in report.findings)


def test_english_hover_link_is_accepted(tmp_path: Path):
    report = _argument(tmp_path, "The {{Wikipedia link|article=Ganzfeld effect}} describes a perceptual condition.", lang="en")
    assert not any(f.code == "WDV-MWK-020" for f in report.findings)


def test_wrong_language_parameter_is_rejected(tmp_path: Path):
    report = _argument(tmp_path, "Une {{Lien Wikipédia|article=Monnaie locale|displayed-text=monnaie locale}} circule.")
    assert any(f.code == "WDV-MWK-020" for f in report.findings)


def test_redundant_displayed_text_is_rejected(tmp_path: Path):
    report = _argument(tmp_path, "L'{{Lien Wikipédia|article=Effet Ganzfeld|texte-affiché=effet Ganzfeld}} est étudié.")
    assert any(f.code == "WDV-MWK-020" and "redondant" in f.message for f in report.findings)


def test_hover_link_inside_ref_is_rejected(tmp_path: Path):
    report = _argument(tmp_path, "Une notion est citée.<ref>{{Lien Wikipédia|article=Réalisme}}</ref>")
    assert any(f.code == "WDV-MWK-020" and "note" in f.message for f in report.findings)


def test_1224_introduction_review_requires_hover_attestations():
    entry = {
        "language":"fr","subject_and_scope_defined":True,"debate_question_explained":True,
        "history_and_evolution_addressed":True,"current_state_addressed_or_not_applicable":True,
        "stakes_explained":True,"factual_claims_referenced":True,"progression_coherent":True,
        "no_argument_tree_mirroring":True,"no_topic_specific_checklist":True,
        "complete_topic_fits_heading":True,"debate_sections_precise":True,
        "documentation_proportionate_to_literature":True,
        "documentation_family_notes":{"bibliography":"Une note suffisamment longue pour le test.","webliography":"Une note suffisamment longue pour le test.","videography":"Une note suffisamment longue pour le test."},
        "common_acronym":None,"common_acronym_used_or_not_applicable":True,
        "topic_is_nominal_label":True,"conventional_topic_label_used_or_not_applicable":True,
        "complete_topic_lowercase_initial_or_justified":True,"topic_label_rationale":"Un libellé nominal conventionnel.",
        "subsections":[{"title":"Définition","purpose":"Définir le sujet.","necessary_for_understanding":True,"technical_or_specialized":False,"relevance_to_debate_explained":True}],
    }
    review={"normative_revision":"1.2.24","entries":[entry]}
    issues=validate_introduction_review_data(review,{"fr":["Définition"]},norm="1.2.24",complete_topics={"fr":"le réalisme"},topics={"fr":"Réalisme"})
    assert any(i["reason"]=="wikipedia_hover_links_reviewed" for i in issues)


def test_1224_summary_review_requires_hover_attestations():
    decision={"status":"approved","thesis_first":True,"general_public_style":True,"sentence_rhythm_reviewed":True,"technical_terms_reviewed":True,"opening_develops_title":True,"example_or_data_reviewed":True,"assertive_tone_reviewed":True,"no_artificial_example_or_number":True,"no_polemical_overstatement":True,"conviction_visible":True,"forceful_expression":"Une expression ferme présente.","note":"Résumé relu selon la norme."}
    review={"normative_revision":"1.2.24","entries":[{"id":"A0001","languages":{"fr":decision}}]}
    issues=validate_summary_style_review_data(review,[{"id":"A0001"}],{"A0001":{"fr"}},norm="1.2.24",summaries={("A0001","fr"):"Une expression ferme présente dans le résumé."})
    assert any(i["reason"]=="wikipedia_hover_links_reviewed" for i in issues)
