from pathlib import Path

from wikidebia_validator.package import PackageContext
from wikidebia_validator.report import Report
from wikidebia_validator.wikicode import parse_template, validate_template_shape


def _ctx(tmp_path: Path, french: str, *, target_origin: str = "new", preserved=None) -> tuple[PackageContext, dict]:
    (tmp_path / "fr.wiki").write_text(french, encoding="utf-8")
    page = {
        "page_id": "A0001",
        "page_type": "argument",
        "language": "en",
        "file_path": "en.wiki",
        "page_origin": target_origin,
        "preserved_parameters": preserved or {},
    }
    manifest = {
        "normative_versions": {"consolidated_norm": "1.2.70"},
        "translation_status": {"en": "ready"},
        "pages": [
            {"page_id": "A0001", "page_type": "argument", "language": "fr", "file_path": "fr.wiki"},
            page,
        ],
    }
    return PackageContext(
        root=tmp_path,
        report=Report("0.4.73", str(tmp_path), ["wikicode"]),
        cache={"manifest.json": manifest},
    ), page


def _french_source() -> str:
    return """{{Argument
|initialisation=Objection@12345
|avertissements-argument=Argument généré par IA
|résumé=Résumé français.
|rubriques=Philosophie
|mots-clés=Dieu
|date-création=2020-01-01
}}"""


def _english_target(*, initialization: bool = False, creation_date: str = "2026-08-10") -> str:
    rows = ["{{Argument"]
    if initialization:
        rows.append("|initialization=Objection@12345")
    rows.extend([
        "|argument-warnings=Argument generated by AI",
        "|summary=English summary.",
        "|sections=Philosophy",
        "|keywords=God",
        f"|creation-date={creation_date}",
        "}}",
    ])
    return "\n".join(rows)


def test_new_english_translation_does_not_project_french_initialisation(tmp_path):
    ctx, page = _ctx(tmp_path, _french_source())
    target = _english_target(initialization=False)
    validate_template_shape(ctx, parse_template(target), "en", "argument", "en.wiki", page)
    assert not any(
        f.code == "WDV-MWK-023" and "initialization" in f.message
        for f in ctx.report.findings
    ), ctx.report.to_text()


def test_new_english_translation_rejects_cross_wiki_initialization(tmp_path):
    ctx, page = _ctx(tmp_path, _french_source())
    target = _english_target(initialization=True)
    validate_template_shape(ctx, parse_template(target), "en", "argument", "en.wiki", page)
    assert any(
        f.code == "WDV-MWK-003" and "initialization" in f.message
        for f in ctx.report.findings
    ), ctx.report.to_text()


def test_new_english_creation_date_is_not_compared_to_french_creation_date(tmp_path):
    ctx, page = _ctx(tmp_path, _french_source())
    target = _english_target(creation_date="2026-08-10")
    validate_template_shape(ctx, parse_template(target), "en", "argument", "en.wiki", page)
    assert not any(
        f.code == "WDV-MWK-023" and "date de création anglaise" in f.message.lower()
        for f in ctx.report.findings
    ), ctx.report.to_text()


def test_preexisting_english_initialization_and_creation_date_remain_preservable(tmp_path):
    from wikidebia_validator.wikicode import PROTECTED_PAGE_PARAMETERS

    french = _french_source()
    target = _english_target(initialization=True, creation_date="2018-04-12")
    tmpl = parse_template(target)
    preserved = {}
    for name in PROTECTED_PAGE_PARAMETERS[("en", "argument")]:
        value = tmpl.one(name)
        preserved[name] = {"present": value is not None, "value": value}
    ctx, page = _ctx(tmp_path, french, target_origin="preexisting", preserved=preserved)
    validate_template_shape(ctx, tmpl, "en", "argument", "en.wiki", page)
    assert not any(
        f.code in {"WDV-MWK-003", "WDV-MWK-023"} and ("initialization" in f.message or "date de création anglaise" in f.message.lower())
        for f in ctx.report.findings
    ), ctx.report.to_text()
