from __future__ import annotations

import json
from pathlib import Path

from wikidebia_validator.package import PackageContext
from wikidebia_validator.report import Report
from wikidebia_validator.wikicode import (
    PROTECTED_PAGE_PARAMETERS,
    TOP,
    parse_template,
    validate_template_shape,
)


def _ctx(tmp_path: Path, language: str, name: str) -> PackageContext:
    review = tmp_path / "reviews/argument_name_discovery_review.json"
    review.parent.mkdir(parents=True, exist_ok=True)
    review.write_text(json.dumps({
        "entries": [{
            "language": language,
            "page_id": "A0001",
            "title": "Argument topic",
            "page_origin": "new",
            "search_reviewed": True,
            "search_queries": ["query one", "query two"],
            "search_scope_note": "Relevant academic terminology was checked.",
            "outcome": "known_name",
            "name": name,
            "evidence": [{"source": "Academic source", "label_as_used": name, "locator": "p. 1", "url": None}],
            "same_reasoning_confirmed": True,
            "non_invented_label_confirmed": True,
            "language_fit_confirmed": True,
            "rationale": "The same reasoning is explicitly designated by this established name.",
        }]
    }, ensure_ascii=False), encoding="utf-8")
    manifest = {
        "normative_versions": {"consolidated_norm": "1.2.58"},
        "editorial_controls": {"argument_name_discovery_path": "reviews/argument_name_discovery_review.json"},
    }
    (tmp_path / "manifest.json").write_text(json.dumps(manifest), encoding="utf-8")
    return PackageContext(tmp_path, Report("0.4.62", str(tmp_path), ["wikicode"]))


def test_1258_canonical_parameter_is_second_argument_slot_in_both_languages():
    assert TOP["fr", "argument"]["order"][:3] == ["initialisation", "nom-consacré", "nom"]
    assert TOP["en", "argument"]["order"][:3] == ["initialization", "established-name", "name"]
    assert PROTECTED_PAGE_PARAMETERS["fr", "argument"][:3] == ("initialisation", "nom-consacré", "nom")
    assert PROTECTED_PAGE_PARAMETERS["en", "argument"][:3] == ("initialization", "established-name", "name")


def test_1258_new_french_argument_accepts_nom_consacre(tmp_path: Path):
    ctx = _ctx(tmp_path, "fr", "Argument cosmologique")
    page = {"page_id": "A0001", "page_type": "argument", "language": "fr", "page_origin": "new", "preserved_parameters": {}}
    tmpl = parse_template("""{{Argument
|nom-consacré=Argument cosmologique
|avertissements-argument=Argument généré par IA
|résumé=Un résumé complet développe le raisonnement de cet argument.
|rubriques=Philosophie
|mots-clés=Dieu
|date-création=2026-08-10
}}""")
    validate_template_shape(ctx, tmpl, "fr", "argument", "argument.wiki", page)
    assert not any(item.code in {"WDV-MWK-003", "WDV-EDT-032"} for item in ctx.report.findings), ctx.report.to_text()


def test_1258_new_french_argument_rejects_legacy_nom(tmp_path: Path):
    ctx = _ctx(tmp_path, "fr", "Argument cosmologique")
    page = {"page_id": "A0001", "page_type": "argument", "language": "fr", "page_origin": "new", "preserved_parameters": {}}
    tmpl = parse_template("""{{Argument
|nom=Argument cosmologique
|avertissements-argument=Argument généré par IA
|résumé=Un résumé complet développe le raisonnement de cet argument.
|rubriques=Philosophie
|mots-clés=Dieu
|date-création=2026-08-10
}}""")
    validate_template_shape(ctx, tmpl, "fr", "argument", "argument.wiki", page)
    assert any(item.code == "WDV-MWK-003" and "historique nom" in item.message for item in ctx.report.findings)


def test_1258_new_english_argument_accepts_established_name(tmp_path: Path):
    ctx = _ctx(tmp_path, "en", "Cosmological argument")
    page = {"page_id": "A0001", "page_type": "argument", "language": "en", "page_origin": "new", "preserved_parameters": {}}
    tmpl = parse_template("""{{Argument
|established-name=Cosmological argument
|argument-warnings=Argument generated by AI
|summary=A complete summary explains the reasoning of this argument.
|sections=Philosophy
|keywords=God
|creation-date=2026-08-10
}}""")
    validate_template_shape(ctx, tmpl, "en", "argument", "argument.wiki", page)
    assert not any(item.code in {"WDV-MWK-003", "WDV-EDT-032"} for item in ctx.report.findings), ctx.report.to_text()


def test_1258_new_english_argument_rejects_legacy_name(tmp_path: Path):
    ctx = _ctx(tmp_path, "en", "Cosmological argument")
    page = {"page_id": "A0001", "page_type": "argument", "language": "en", "page_origin": "new", "preserved_parameters": {}}
    tmpl = parse_template("""{{Argument
|name=Cosmological argument
|argument-warnings=Argument generated by AI
|summary=A complete summary explains the reasoning of this argument.
|sections=Philosophy
|keywords=God
|creation-date=2026-08-10
}}""")
    validate_template_shape(ctx, tmpl, "en", "argument", "argument.wiki", page)
    assert any(item.code == "WDV-MWK-003" and "historique name" in item.message for item in ctx.report.findings)


def test_1258_preexisting_legacy_nom_is_preserved_without_migration(tmp_path: Path):
    ctx = PackageContext(tmp_path, Report("0.4.62", str(tmp_path), ["wikicode"]), cache={"manifest.json": {"normative_versions": {"consolidated_norm": "1.2.58"}}})
    page = {
        "page_id": "A0001", "page_type": "argument", "language": "fr", "page_origin": "preexisting",
        "preserved_parameters": {
            "initialisation": {"present": False, "value": None},
            "nom": {"present": True, "value": "Argument cosmologique"},
            "avertissements-titre": {"present": False, "value": None},
            "avertissements-argument": {"present": False, "value": None},
            "avertissements-résumé": {"present": False, "value": None},
            "avertissements-références": {"present": False, "value": None},
            "avertissements-justifications": {"present": False, "value": None},
            "avertissements-objections": {"present": False, "value": None},
            "débat-détaillé": {"present": False, "value": None},
            "interlangue": {"present": False, "value": None},
            "date-création": {"present": True, "value": "2020-01-01"},
        },
    }
    tmpl = parse_template("""{{Argument
|nom=Argument cosmologique
|résumé=Résumé historique conservé exactement.
|rubriques=Philosophie
|mots-clés=Dieu
|date-création=2020-01-01
}}""")
    validate_template_shape(ctx, tmpl, "fr", "argument", "argument.wiki", page)
    assert not any(item.code == "WDV-MWK-023" for item in ctx.report.findings), ctx.report.to_text()
    assert not any(item.code == "WDV-MWK-003" and "nom" in item.message for item in ctx.report.findings), ctx.report.to_text()


def test_1258_canonical_and_legacy_aliases_cannot_coexist(tmp_path: Path):
    ctx = _ctx(tmp_path, "fr", "Argument cosmologique")
    page = {"page_id": "A0001", "page_type": "argument", "language": "fr", "page_origin": "new", "preserved_parameters": {}}
    tmpl = parse_template("""{{Argument
|nom-consacré=Argument cosmologique
|nom=Argument cosmologique
|avertissements-argument=Argument généré par IA
|résumé=Un résumé complet développe le raisonnement de cet argument.
|rubriques=Philosophie
|mots-clés=Dieu
|date-création=2026-08-10
}}""")
    validate_template_shape(ctx, tmpl, "fr", "argument", "argument.wiki", page)
    assert any(item.code == "WDV-MWK-003" and "ne peuvent pas coexister" in item.message for item in ctx.report.findings)
