from wikidebia_validator.report import Report
from wikidebia_validator.wikicode import ACTIVE_TOP, PROTECTED_PAGE_PARAMETERS, parse_template, validate_template_shape


class FakeContext:
    def __init__(self, norm: str):
        self.report = Report("0.4.72", "test-fixture", ["wikicode"])
        self._norm = norm

    def manifest(self):
        return {"normative_versions": {"consolidated_norm": self._norm}}


def _debate(expanded_parameter: str) -> str:
    return f"""{{{{Debate
|topic=Philosophical realism
|{expanded_parameter}=philosophical realism
|progress=Constructed debate
|debate-warnings=Debate generated by AI
|introduction={{{{Subsection
|title=Definition
|content=Conceptual introduction.
}}}}
|pro-arguments={{{{Pro argument
|page=A complete pro title
|displayed-title=A pro title is defensible
}}}}
|con-arguments={{{{Con argument
|page=A complete con title
|displayed-title=A con title is defensible
}}}}
|sections=Philosophy
|keywords=realism, philosophy
|creation-date=2026-08-10
}}}}
"""


def test_current_structure_uses_renamed_mediawiki_parameters():
    assert "sujet-développé" in ACTIVE_TOP["fr", "debate"]["order"]
    assert "sujet-complet" not in ACTIVE_TOP["fr", "debate"]["order"]
    assert "expanded-topic" in ACTIVE_TOP["en", "debate"]["order"]
    assert "complete-topic" not in ACTIVE_TOP["en", "debate"]["order"]
    assert "débat-dédié" in ACTIVE_TOP["fr", "argument"]["order"]
    assert "débat-détaillé" not in ACTIVE_TOP["fr", "argument"]["order"]
    assert "dedicated-debate" in ACTIVE_TOP["en", "argument"]["order"]
    assert "detailed-debate" not in ACTIVE_TOP["en", "argument"]["order"]


def test_pre_1269_package_remains_readable_with_complete_topic():
    ctx = FakeContext("1.2.68")
    validate_template_shape(ctx, parse_template(_debate("complete-topic")), "en", "debate", "debate.wiki")
    assert not {"WDV-MWK-003", "WDV-MWK-004", "WDV-EDT-018"} & {f.code for f in ctx.report.findings}


def test_current_package_accepts_expanded_topic():
    ctx = FakeContext("1.2.69")
    validate_template_shape(ctx, parse_template(_debate("expanded-topic")), "en", "debate", "debate.wiki")
    assert not {"WDV-MWK-003", "WDV-MWK-004", "WDV-EDT-018"} & {f.code for f in ctx.report.findings}


def test_current_package_rejects_legacy_complete_topic():
    ctx = FakeContext("1.2.69")
    validate_template_shape(ctx, parse_template(_debate("complete-topic")), "en", "debate", "debate.wiki")
    assert {"WDV-MWK-003", "WDV-MWK-004"} & {f.code for f in ctx.report.findings}


def _fr_debate(expanded_parameter: str, *, extra: str = "") -> str:
    return f"""{{{{Débat
|sujet=Réalisme philosophique
|{expanded_parameter}=le réalisme philosophique
{extra}|avancement=Débat construit
|avertissements-débat=Débat généré par IA
|introduction={{{{Sous-partie
|titre=Définition
|contenu=Introduction conceptuelle.
}}}}
|arguments-pour={{{{Argument pour
|page=Un titre pour complet
|titre-affiché=Un argument pour est défendable
}}}}
|arguments-contre={{{{Argument contre
|page=Un titre contre complet
|titre-affiché=Un argument contre est défendable
}}}}
|rubriques=Philosophie
|mots-clés=réalisme, philosophie
|date-création=2026-08-10
}}}}
"""


def _argument(lang: str, dedicated_parameter: str, *, extra: str = "") -> str:
    if lang == "fr":
        return f"""{{{{Argument
|avertissements-argument=Argument généré par IA
|résumé=Résumé autonome.
|{dedicated_parameter}=Débat consacré
{extra}|rubriques=Philosophie
|mots-clés=preuve, philosophie
|date-création=2026-08-10
}}}}
"""
    return f"""{{{{Argument
|argument-warnings=Argument generated by AI
|summary=Standalone summary.
|{dedicated_parameter}=Dedicated discussion
{extra}|sections=Philosophy
|keywords=proof, philosophy
|creation-date=2026-08-10
}}}}
"""


def test_current_french_debate_accepts_sujet_developpe_and_rejects_sujet_complet():
    good = FakeContext("1.2.69")
    validate_template_shape(good, parse_template(_fr_debate("sujet-développé")), "fr", "debate", "debate.wiki")
    assert not {"WDV-MWK-003", "WDV-MWK-004"} & {f.code for f in good.report.findings}

    old = FakeContext("1.2.69")
    validate_template_shape(old, parse_template(_fr_debate("sujet-complet")), "fr", "debate", "debate.wiki")
    assert {"WDV-MWK-003", "WDV-MWK-004"} & {f.code for f in old.report.findings}


def _preexisting_manifest(lang: str, dedicated_name: str, dedicated_value: str) -> dict:
    protected = list(PROTECTED_PAGE_PARAMETERS[lang, "argument"])
    current_name = "débat-dédié" if lang == "fr" else "dedicated-debate"
    if dedicated_name != current_name:
        protected[protected.index(current_name)] = dedicated_name
    established_current = "nom-consacré" if lang == "fr" else "established-name"
    established_legacy = "nom" if lang == "fr" else "name"
    # Current PROTECTED includes both name aliases; a historical manifest may do so as well.
    preserved = {name: {"present": False, "value": None} for name in protected}
    preserved[dedicated_name] = {"present": True, "value": dedicated_value}
    return {"page_id": "A1", "page_type": "argument", "language": lang, "page_origin": "preexisting", "preserved_parameters": preserved}


def test_dedicated_debate_renames_are_enforced_in_both_languages():
    cases = [
        ("fr", "débat-dédié", "débat-détaillé", "Débat consacré"),
        ("en", "dedicated-debate", "detailed-debate", "Dedicated discussion"),
    ]
    for lang, current_name, old_name, value in cases:
        current = FakeContext("1.2.69")
        validate_template_shape(current, parse_template(_argument(lang, current_name)), lang, "argument", "argument.wiki", _preexisting_manifest(lang, current_name, value))
        assert "WDV-MWK-003" not in {f.code for f in current.report.findings}

        legacy_current = FakeContext("1.2.69")
        validate_template_shape(legacy_current, parse_template(_argument(lang, old_name)), lang, "argument", "argument.wiki", _preexisting_manifest(lang, old_name, value))
        assert "WDV-MWK-003" in {f.code for f in legacy_current.report.findings}

        historical = FakeContext("1.2.68")
        validate_template_shape(historical, parse_template(_argument(lang, old_name)), lang, "argument", "argument.wiki", _preexisting_manifest(lang, old_name, value))
        codes = {f.code for f in historical.report.findings}
        assert "WDV-MWK-003" not in codes
        assert not any(f.code == "WDV-MWK-023" and "préserv" in f.message for f in historical.report.findings)


def test_current_output_rejects_coexistence_of_old_and_new_parameter_names():
    debate = FakeContext("1.2.69")
    validate_template_shape(
        debate,
        parse_template(_debate("expanded-topic").replace("|progress=", "|complete-topic=philosophical realism\n|progress=")),
        "en",
        "debate",
        "debate.wiki",
    )
    assert "WDV-MWK-003" in {f.code for f in debate.report.findings}

    argument = FakeContext("1.2.69")
    validate_template_shape(
        argument,
        parse_template(_argument("en", "dedicated-debate").replace("|sections=", "|detailed-debate=Dedicated discussion\n|sections=")),
        "en",
        "argument",
        "argument.wiki",
    )
    assert "WDV-MWK-003" in {f.code for f in argument.report.findings}
