from __future__ import annotations

import json
from pathlib import Path

from wikidebia_validator import __version__
from wikidebia_validator.package import PackageContext
from wikidebia_validator.report import Report
from wikidebia_validator.wikicode import (
    _validate_citations_against_locks,
    parse_template,
    validate_template_shape,
)


def context(tmp_path: Path, lang: str, citation: dict) -> PackageContext:
    (tmp_path / "data").mkdir(parents=True)
    lock_name = "fr_content_lock.json" if lang == "fr" else "en_content_lock.json"
    (tmp_path / f"data/{lock_name}").write_text(
        json.dumps({"arguments": [{"id": "A0001", "citations": [citation]}]}, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    return PackageContext(
        root=tmp_path,
        report=Report("0.4.44", tmp_path.name, ["wikicode"]),
        cache={"manifest.json": {"normative_versions": {"consolidated_norm": "1.2.27"}}},
    )


def english_expected() -> dict:
    source_parameters = [
        {"name": "citation", "value": "Texte source."},
        {"name": "auteurs", "value": "Auteur inchangé"},
        {"name": "ouvrage", "value": "Original Work"},
        {"name": "date", "value": "25 juin 2012"},
        {"name": "avertissements-citation", "value": "Texte abrégé"},
    ]
    parameters = [
        {"name": "citation", "value": "Translated text."},
        {"name": "auteurs", "value": "Auteur inchangé"},
        {"name": "ouvrage", "value": "Original Work"},
        {"name": "date", "value": "25 June 2012"},
        {"name": "avertissements-citation", "value": "Texte abrégé, Citation traduite par IA"},
    ]
    return {
        "id": "A0001-C001",
        "parameters": parameters,
        "avertissements-citation": "Texte abrégé, Citation traduite par IA",
        "source": {"source_parameters": source_parameters},
    }


def argument(quote: str, *, lang: str = "en") -> str:
    if lang == "en":
        return f"""{{{{Argument
|argument-warnings=Argument generated by AI
|summary=A complete English summary explains the reasoning.
|quotes={quote}
|sections=Philosophy
|keywords=freedom, responsibility
|creation-date=2026-08-03
}}}}"""
    return f"""{{{{Argument
|avertissements-argument=Argument généré par IA
|résumé=Un résumé français complet explique le raisonnement.
|citations={quote}
|rubriques=Philosophie
|mots-clés=liberté, responsabilité
|interlangue={{{{Lien interlangue
|langue=en
|page=English title
}}}}
|date-création=2026-08-03
}}}}"""


def test_validator_version_and_active_norm_1227():
    assert __version__ == "0.4.44"
    root = Path(__file__).resolve().parents[1] / "normative_reference/01_normes"
    assert [path.name for path in root.glob("WIKIDEBIA_NORME_CONSOLIDEE_*.md")] == ["WIKIDEBIA_NORME_CONSOLIDEE_1.2.41.md"]


def test_english_citation_matching_lock_is_accepted(tmp_path: Path):
    expected = english_expected()
    raw = """{{Quote
|citation=Translated text.
|auteurs=Auteur inchangé
|ouvrage=Original Work
|date=25 June 2012
|avertissements-citation=Texte abrégé, Citation traduite par IA
}}"""
    ctx = context(tmp_path, "en", expected)
    tmpl = parse_template(argument(raw))
    validate_template_shape(ctx, tmpl, "en", "argument", "output/en/arguments/A0001.wiki")
    _validate_citations_against_locks(ctx, tmpl, "output/en/arguments/A0001.wiki", "en", "A0001")
    assert not any(item.code == "WDV-MWK-021" for item in ctx.report.findings)
    assert not any(item.code == "WDV-MWK-003" and "quotes" in item.message for item in ctx.report.findings)


def test_english_citation_rejects_changed_documentary_parameter(tmp_path: Path):
    expected = english_expected()
    raw = """{{Quote
|citation=Translated text.
|auteurs=Translated author
|ouvrage=Original Work
|date=25 June 2012
|avertissements-citation=Texte abrégé, Citation traduite par IA
}}"""
    ctx = context(tmp_path, "en", expected)
    tmpl = parse_template(argument(raw))
    _validate_citations_against_locks(ctx, tmpl, "output/en/arguments/A0001.wiki", "en", "A0001")
    assert any(item.code == "WDV-MWK-021" for item in ctx.report.findings)


def test_english_citation_rejects_missing_translation_warning(tmp_path: Path):
    expected = english_expected()
    raw = """{{Quote
|citation=Translated text.
|auteurs=Auteur inchangé
|ouvrage=Original Work
|date=25 June 2012
|avertissements-citation=Texte abrégé
}}"""
    ctx = context(tmp_path, "en", expected)
    tmpl = parse_template(argument(raw))
    _validate_citations_against_locks(ctx, tmpl, "output/en/arguments/A0001.wiki", "en", "A0001")
    assert any(item.code == "WDV-MWK-021" and "Citation traduite par IA" in item.message for item in ctx.report.findings)


def test_citations_remain_forbidden_before_norm_1227(tmp_path: Path):
    ctx = PackageContext(
        root=tmp_path,
        report=Report("0.4.44", tmp_path.name, ["wikicode"]),
        cache={"manifest.json": {"normative_versions": {"consolidated_norm": "1.2.26"}}},
    )
    raw = "{{Citation\n|citation=Texte.\n}}"
    tmpl = parse_template(argument(raw, lang="fr"))
    validate_template_shape(ctx, tmpl, "fr", "argument", "argument.wiki")
    assert any(item.code == "WDV-MWK-003" and "citations" in item.message for item in ctx.report.findings)


def test_english_citation_model_name_must_be_quote(tmp_path: Path):
    expected = english_expected()
    raw = """{{Citation
|citation=Translated text.
|auteurs=Auteur inchangé
|ouvrage=Original Work
|date=25 June 2012
|avertissements-citation=Texte abrégé, Citation traduite par IA
}}"""
    ctx = context(tmp_path, "en", expected)
    tmpl = parse_template(argument(raw))
    validate_template_shape(ctx, tmpl, "en", "argument", "output/en/arguments/A0001.wiki")
    _validate_citations_against_locks(ctx, tmpl, "output/en/arguments/A0001.wiki", "en", "A0001")
    assert any(item.code in {"WDV-MWK-012", "WDV-MWK-021"} for item in ctx.report.findings)


def test_historical_quote_parameters_remain_recognized(tmp_path: Path):
    ctx = PackageContext(
        root=tmp_path,
        report=Report("0.4.44", tmp_path.name, ["wikicode"]),
        cache={"manifest.json": {"normative_versions": {"consolidated_norm": "1.2.26"}}},
    )
    raw = """{{Quote
|quote=Original English quotation.
|authors=Original Author
|work=Original Work
|date=1971
}}"""
    tmpl = parse_template(argument(raw, lang="en"))
    validate_template_shape(ctx, tmpl, "en", "argument", "argument.wiki")
    assert not any(
        item.code == "WDV-MWK-012" and ("Sous-modèle" in item.message or "Paramètre inconnu" in item.message)
        for item in ctx.report.findings
    )
