from wikidebia_validator.editorial import _validate_intro_references
from wikidebia_validator.report import Report


class Context:
    def __init__(self, content: str, language: str = "fr"):
        self.language = language
        self.text = self._page(content, language)
        self.report = Report("0.4.10", "test-fixture-1210", ["editorial"])

    @staticmethod
    def _page(content: str, language: str) -> str:
        if language == "en":
            return "{{Debate\n|topic=Surrogacy\n|complete-topic=the authorization of surrogacy\n|progress=Constructed debate\n|debate-warnings=Debate generated by AI\n|introduction={{Subsection\n|title=Definition\n|content=" + content + "\n}}\n|pro-arguments={{Pro argument\n|page=A complete favorable reason\n|displayed-title=A favorable reason\n}}\n|con-arguments={{Con argument\n|page=A complete unfavorable reason\n|displayed-title=An unfavorable reason\n}}\n|sections=Society\n|keywords=surrogacy\n|creation-date=2026-07-30\n}}\n"
        return "{{Débat\n|sujet=Gestation pour autrui\n|sujet-complet=l’autorisation de la GPA\n|avancement=Débat construit\n|avertissements-débat=Débat généré par IA\n|introduction={{Sous-partie\n|titre=Définition\n|contenu=" + content + "\n}}\n|arguments-pour={{Argument pour\n|page=Une raison favorable complète\n|titre-affiché=Une raison favorable\n}}\n|arguments-contre={{Argument contre\n|page=Une raison défavorable complète\n|titre-affiché=Une raison défavorable\n}}\n|rubriques=Société\n|mots-clés=gestation pour autrui\n|interlangue={{Lien interlangue\n|langue=en\n|page=Should surrogacy be permitted?\n}}\n|date-création=2026-07-30\n}}\n"

    def manifest(self):
        return {"normative_versions": {"consolidated_norm": "1.2.10"}, "pages": [{"page_type": "debate", "language": self.language, "file_path": f"output/{self.language}/debate.wiki"}]}

    def exists(self, rel):
        return rel == f"output/{self.language}/debate.wiki"

    def read_text(self, rel):
        return self.text


def validate(content: str, language: str = "fr"):
    ctx = Context(content, language)
    metrics = _validate_intro_references(ctx, ctx.manifest(), {"introduction_references": {"required": True}})
    return ctx, metrics


def test_norm_1210_accepts_direct_reference_text_in_french_and_english():
    fr, metrics_fr = validate("Fait documenté<ref>Jean Dupont, « Titre », ''Revue'', 25 juin 2012, p. 36-37, [https://example.org texte intégral].</ref>.")
    assert metrics_fr["fr"]["invalid_direct_reference_notes"] == []
    assert not any(f.code in {"WDV-EDT-010", "WDV-DOC-005"} for f in fr.report.findings)
    en, metrics_en = validate("A documented fact.<ref>Jane Smith, “Title”, ''Journal'', 25 June 2012, pp. 36–37, [https://example.org full text].</ref>", "en")
    assert metrics_en["en"]["invalid_direct_reference_notes"] == []
    assert not any(f.code in {"WDV-EDT-010", "WDV-DOC-005"} for f in en.report.findings)


def test_norm_1210_rejects_generic_and_specialized_templates():
    for body in ("{{Référence|auteurs=A|titre=T|date=25 juin 2012}}", "{{Référence bibliographique|auteurs=A|ouvrage=O|date=25 juin 2012}}"):
        ctx, metrics = validate(f"Fait documenté<ref>{body}</ref>.")
        assert metrics["fr"]["invalid_direct_reference_notes"]
        assert any(f.code == "WDV-EDT-010" for f in ctx.report.findings)


def test_norm_1210_allows_named_direct_reference_and_reuse():
    ctx, metrics = validate("Premier fait<ref name=\"dupont\">Jean Dupont, « Titre », 25 juin 2012.</ref>. Second fait<ref name=\"dupont\" />.")
    assert metrics["fr"]["undefined_named_references"] == []
    assert not any(f.code == "WDV-EDT-010" for f in ctx.report.findings)


def test_norm_1210_rejects_machine_date_in_direct_text_but_not_creation_date():
    ctx, metrics = validate("Fait documenté<ref>Jean Dupont, « Titre », 2012-06-25, [https://example.org texte intégral].</ref>.")
    assert metrics["fr"]["machine_documentary_dates"]
    assert any(f.code == "WDV-DOC-005" for f in ctx.report.findings)
    assert "|date-création=2026-07-30" in ctx.text
