from pathlib import Path
from wikidebia_validator.wikicode import TOP

def test_active_norm_is_117():
    root=Path(__file__).parents[1]/"normative_reference"/"01_normes"
    assert sorted(p.name for p in root.glob("WIKIDEBIA_NORME_CONSOLIDEE_*.md"))==["WIKIDEBIA_NORME_CONSOLIDEE_1.2.15.md"]

def test_fixed_warning_values_use_by_par():
    assert TOP[("fr","debate")]["fixed"]["avertissements-débat"]=="Débat généré par IA"
    assert TOP[("fr","argument")]["fixed"]["avertissements-argument"]=="Argument généré par IA"
    assert TOP[("en","debate")]["fixed"]["debate-warnings"]=="Debate generated by AI"
    assert TOP[("en","argument")]["fixed"]["argument-warnings"]=="Argument generated by AI"

def test_active_runtime_rejects_old_warning_wording():
    root=Path(__file__).parents[1]
    text="\n".join(p.read_text(encoding="utf-8") for p in [root/"src/wikidebia_validator/wikicode.py",root/"normative_reference/00_sources_reference/DECISIONS_CONVERSATION_CONSOLIDEES.md",root/"normative_reference/01_normes/profils_rendu_wikidebia.md"])
    assert "généré avec IA" not in text
    assert "generated with AI" not in text
