from __future__ import annotations

import json
from pathlib import Path

from wikidebia_validator.package import PackageContext
from wikidebia_validator.report import Report
from wikidebia_validator.wikicode import _validate_citations_against_locks, parse_template, validate_template_shape


def _expected() -> dict:
    source_parameters = [
        {"name": "citation", "value": "Texte source."},
        {"name": "auteurs", "value": "Auteur inchangé"},
        {"name": "article", "value": "Original Article"},
        {"name": "ouvrage", "value": "Original Work"},
        {"name": "volume", "value": "2"},
        {"name": "numéro", "value": "3"},
        {"name": "page", "value": "11-25"},
        {"name": "localisation", "value": "chapitre 2"},
        {"name": "édition", "value": "Original Publisher"},
        {"name": "lieu", "value": "Paris"},
        {"name": "date", "value": "25 juin 2012"},
        {"name": "lien", "value": "https://example.org"},
        {"name": "avertissements-citation", "value": "Texte abrégé"},
    ]
    parameters = [
        {"name": "quote", "value": "Translated text."},
        {"name": "authors", "value": "Auteur inchangé"},
        {"name": "article", "value": "Original Article"},
        {"name": "work", "value": "Original Work"},
        {"name": "volume", "value": "2"},
        {"name": "issue", "value": "3"},
        {"name": "page", "value": "11-25"},
        {"name": "location", "value": "chapitre 2"},
        {"name": "publisher", "value": "Original Publisher"},
        {"name": "place", "value": "Paris"},
        {"name": "date", "value": "25 June 2012"},
        {"name": "link", "value": "https://example.org"},
        {"name": "warnings", "value": "Texte abrégé, Citation traduite par IA"},
    ]
    return {
        "id": "A0001-C001",
        "parameters": parameters,
        "warnings": "Texte abrégé, Citation traduite par IA",
        "source": {"source_parameters": source_parameters},
    }


def _context(tmp_path: Path) -> PackageContext:
    (tmp_path / "data").mkdir(parents=True)
    (tmp_path / "data/en_content_lock.json").write_text(
        json.dumps({"arguments": [{"id": "A0001", "citations": [_expected()]}]}, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    (tmp_path / "manifest.json").write_text(
        json.dumps({"normative_versions": {"consolidated_norm": "1.2.30"}}, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    return PackageContext(
        root=tmp_path,
        report=Report("0.4.36", tmp_path.name, ["wikicode"]),
        cache={"manifest.json": {"normative_versions": {"consolidated_norm": "1.2.30"}}},
    )


def _argument(quote: str) -> str:
    return f"""{{{{Argument
|argument-warnings=Argument generated by AI
|summary=A complete English summary explains the reasoning.
|quotes={quote}
|sections=Philosophy
|keywords=freedom, responsibility
|creation-date=2026-08-04
}}}}"""


def test_english_quote_uses_only_english_template_parameters(tmp_path: Path):
    raw = """{{Quote
|quote=Translated text.
|authors=Auteur inchangé
|article=Original Article
|work=Original Work
|volume=2
|issue=3
|page=11-25
|location=chapitre 2
|publisher=Original Publisher
|place=Paris
|date=25 June 2012
|link=https://example.org
|warnings=Texte abrégé, Citation traduite par IA
}}"""
    ctx = _context(tmp_path)
    tmpl = parse_template(_argument(raw))
    validate_template_shape(ctx, tmpl, "en", "argument", "output/en/arguments/A0001.wiki")
    _validate_citations_against_locks(ctx, tmpl, "output/en/arguments/A0001.wiki", "en", "A0001")
    assert not any(item.code in {"WDV-MWK-003", "WDV-MWK-021"} for item in ctx.report.findings)


def test_english_quote_rejects_french_parameter_names(tmp_path: Path):
    raw = """{{Quote
|citation=Translated text.
|auteurs=Auteur inchangé
|article=Original Article
|ouvrage=Original Work
|volume=2
|numéro=3
|page=11-25
|localisation=chapitre 2
|édition=Original Publisher
|lieu=Paris
|date=25 June 2012
|lien=https://example.org
|avertissements-citation=Texte abrégé, Citation traduite par IA
}}"""
    ctx = _context(tmp_path)
    tmpl = parse_template(_argument(raw))
    _validate_citations_against_locks(ctx, tmpl, "output/en/arguments/A0001.wiki", "en", "A0001")
    assert any(item.code == "WDV-MWK-021" for item in ctx.report.findings)


def test_english_quote_preserves_documentary_values_after_parameter_mapping(tmp_path: Path):
    raw = """{{Quote
|quote=Translated text.
|authors=Auteur traduit à tort
|article=Original Article
|work=Original Work
|volume=2
|issue=3
|page=11-25
|location=chapitre 2
|publisher=Original Publisher
|place=Paris
|date=25 June 2012
|link=https://example.org
|warnings=Texte abrégé, Citation traduite par IA
}}"""
    ctx = _context(tmp_path)
    tmpl = parse_template(_argument(raw))
    _validate_citations_against_locks(ctx, tmpl, "output/en/arguments/A0001.wiki", "en", "A0001")
    assert any(item.code == "WDV-MWK-021" and "valeur" in item.message for item in ctx.report.findings)


def _debate(introduction: str) -> str:
    return f"""{{{{Debate
|topic=Test debate
|complete-topic=the test debate
|progress=Constructed debate
|debate-warnings=Debate generated by AI
|introduction={introduction}
|wikipedia-articles={{{{Wikipedia article|page=Debate}}}}
|pro-arguments={{{{Pro argument|page=A claim|displayed-title=A claim supports the proposition}}}}
|con-arguments={{{{Con argument|page=A counterclaim|displayed-title=A counterclaim opposes the proposition}}}}
|sections=Philosophy
|keywords=debate, reasoning, argument, philosophy, logic
|creation-date=2026-08-04
}}}}"""


def test_english_debate_rejects_french_subsection_model(tmp_path: Path):
    ctx = _context(tmp_path)
    tmpl = parse_template(_debate("{{Sous-partie|titre=Definition|contenu=English content that explains the debate clearly.}}"))
    validate_template_shape(ctx, tmpl, "en", "debate", "output/en/debate/debate.wiki")
    assert any(item.code == "WDV-MWK-022" for item in ctx.report.findings)


def test_english_argument_rejects_french_relation_parameters(tmp_path: Path):
    raw = _argument("{{Quote|quote=Translated text.|authors=Auteur inchangé|date=25 June 2012|warnings=Citation traduite par IA}}")
    raw = raw.replace(
        "|sections=Philosophy",
        "|justifications={{Justification|page=A supporting claim|titre-affiché=Un titre français}}\n|sections=Philosophy",
    )
    ctx = _context(tmp_path)
    tmpl = parse_template(raw)
    validate_template_shape(ctx, tmpl, "en", "argument", "output/en/arguments/A0001.wiki")
    assert any(item.code == "WDV-MWK-022" for item in ctx.report.findings)
