from __future__ import annotations

from wikidebia_validator.wikicode import parse_template, validate_template_shape
from tests.test_norm_1217 import context, debate


def with_authors(value: str) -> str:
    text = debate("|articles-Wikipédia={{Article Wikipédia\n|page=Philosophie\n}}")
    return text.replace("|rubriques=Société", f"|sitographie-ni-pour-ni-contre={{{{Référence sitographique\n|lien=https://example.test\n|auteurs={value}\n|site=Exemple\n}}}}\n|rubriques=Société")


def issues(value: str, norm: str = "1.2.18"):
    ctx = context(norm)
    validate_template_shape(ctx, parse_template(with_authors(value)), "fr", "debate", "debate.wiki")
    return ctx.report.findings


def test_comma_space_author_separator_is_accepted():
    assert not any(i.code == "WDV-DOC-007" for i in issues("Auteur A, Auteur B"))

def test_semicolon_author_separator_is_rejected():
    assert any(i.code == "WDV-DOC-007" for i in issues("Auteur A ; Auteur B"))

def test_comma_without_space_is_rejected():
    assert any(i.code == "WDV-DOC-007" for i in issues("Auteur A,Auteur B"))

def test_space_before_comma_is_rejected():
    assert any(i.code == "WDV-DOC-007" for i in issues("Auteur A , Auteur B"))

def test_fullwidth_comma_is_rejected():
    assert any(i.code == "WDV-DOC-007" for i in issues("Auteur A， Auteur B"))

def test_separator_rule_is_not_retroactive_to_1217():
    assert not any(i.code == "WDV-DOC-007" for i in issues("Auteur A ; Auteur B", "1.2.17"))


def test_active_norm_debate_skeletons_have_nonempty_wikipedia_articles():
    from pathlib import Path
    source = Path(__file__).resolve().parents[1] / "normative_reference" / "01_normes" / "WIKIDEBIA_NORME_CONSOLIDEE_1.2.52.md"
    norm = source.read_text(encoding="utf-8")
    assert "|articles-Wikipédia={{Article Wikipédia" in norm
    assert "|wikipedia-articles={{Wikipedia article" in norm
    assert "|articles-Wikipédia=\n" not in norm
    assert "|wikipedia-articles=\n" not in norm


def test_active_norm_skeletons_do_not_render_related_debates():
    from pathlib import Path
    source = Path(__file__).resolve().parents[1] / "normative_reference" / "01_normes" / "WIKIDEBIA_NORME_CONSOLIDEE_1.2.52.md"
    norm = source.read_text(encoding="utf-8")
    # The terms may appear in prose explaining the prohibition, but never as rendered parameters.
    assert "\n|débats-connexes=" not in norm
    assert "\n|related-debates=" not in norm


def test_json_author_rule_is_generic_not_name_specific():
    findings = issues('["Organisation quelconque", "Personne quelconque"]')
    assert any(i.code == "WDV-DOC-006" for i in findings)

import pytest


@pytest.mark.parametrize(
    ("language", "page", "parameter", "model"),
    [
        ("fr", "debate", "bibliographie-ni-pour-ni-contre", "Référence bibliographique"),
        ("fr", "debate", "sitographie-ni-pour-ni-contre", "Référence sitographique"),
        ("fr", "debate", "vidéographie-ni-pour-ni-contre", "Référence vidéographique"),
        ("en", "debate", "bibliography", "Bibliographical reference"),
        ("en", "debate", "webliography", "Web reference"),
        ("en", "debate", "videography", "Video reference"),
    ],
)
def test_json_author_arrays_are_rejected_in_every_reference_family(language, page, parameter, model):
    author_key = "auteurs" if language == "fr" else "authors"
    if language == "fr":
        base = debate("|articles-Wikipédia={{Article Wikipédia\n|page=Philosophie\n}}")
        required = {
            "Référence bibliographique": "|ouvrage=Ouvrage\n",
            "Référence sitographique": "|lien=https://example.test\n|site=Exemple\n",
            "Référence vidéographique": "|titre=Vidéo\n|lien=https://example.test/video\n",
        }[model]
        value = f"{{{{{model}\n|{author_key}=[\"Organisation A\", \"Personne B\"]\n{required}}}}}"
        source = base.replace("|rubriques=Société", f"|{parameter}={value}\n|rubriques=Société")
    else:
        required = {
            "Bibliographical reference": "|work=Work\n",
            "Web reference": "|link=https://example.test\n|site=Example\n",
            "Video reference": "|title=Video\n|link=https://example.test/video\n",
        }[model]
        value = f"{{{{{model}\n|{author_key}=[\"Organisation A\", \"Person B\"]\n{required}}}}}"
        source = f"""{{{{Debate
|topic=Topic
|complete-topic=the topic
|progress=Constructed debate
|debate-warnings=Debate generated by AI
|introduction={{{{Subsection
|title=Definition
|content=Text.
}}}}
|wikipedia-articles={{{{Wikipedia article
|page=Philosophy
}}}}
|pro-arguments={{{{Pro argument
|page=For
|displayed-title=For
}}}}
|con-arguments={{{{Con argument
|page=Against
|displayed-title=Against
}}}}
|{parameter}={value}
|sections=Society
|keywords=topic
|creation-date=2026-08-01
}}}}"""
    ctx = context("1.2.18")
    validate_template_shape(ctx, parse_template(source), language, page, "debate.wiki")
    assert any(i.code == "WDV-DOC-006" for i in ctx.report.findings)
