from wikidebia_validator.editorial import (
    validate_introduction_review_data,
    validate_summary_style_review_data,
)
from wikidebia_validator.report import Report
from wikidebia_validator.wikicode import parse_template, validate_template_shape
from .current_policy_helpers import complete_summary_decision


class FakeContext:
    def __init__(self):
        self.report = Report("0.4.7", "test-fixture", ["wikicode", "editorial"])

    def manifest(self):
        return {"normative_versions": {"consolidated_norm": "1.2.7"}}


def _english_debate(topic="Parapsychology", complete="the scientific status of parapsychology", sections="History, Philosophy, Psychology, Science, Society"):
    return f"""{{{{Debate
|topic={topic}
|expanded-topic={complete}
|progress=Constructed debate
|debate-warnings=Debate generated by AI
|introduction={{{{Subsection
|title=Definition
|content=Conceptual introduction.
}}}}
|pro-arguments={{{{Pro argument
|page=A complete pro title
|displayed-title=A pro title
}}}}
|con-arguments={{{{Con argument
|page=A complete con title
|displayed-title=A con title
}}}}
|sections={sections}
|keywords=parapsychology, scientific status, scientific method, reproducibility, psi phenomena
|creation-date=2026-07-29
}}}}
"""


def test_norm_127_accepts_alphabetized_sections_and_heading_fragment():
    ctx = FakeContext()
    validate_template_shape(ctx, parse_template(_english_debate()), "en", "debate", "debate.wiki")
    assert not {"WDV-MWK-016", "WDV-MWK-017", "WDV-EDT-018"} & {f.code for f in ctx.report.findings}


def test_norm_127_rejects_unsorted_sections_lowercase_topic_and_question_fragment():
    ctx = FakeContext()
    text = _english_debate(
        topic="parapsychology",
        complete="whether parapsychology meets the criteria for scientific status",
        sections="Science, Philosophy, Psychology, History, Society",
    )
    validate_template_shape(ctx, parse_template(text), "en", "debate", "debate.wiki")
    codes = {f.code for f in ctx.report.findings}
    assert {"WDV-MWK-016", "WDV-MWK-017", "WDV-EDT-018"} <= codes


def _intro_review():
    base = {
        "subject_and_scope_defined": True,
        "debate_question_explained": True,
        "history_and_evolution_addressed": True,
        "current_state_addressed_or_not_applicable": True,
        "stakes_explained": True,
        "factual_claims_referenced": True,
        "progression_coherent": True,
        "no_argument_tree_mirroring": True,
        "no_topic_specific_checklist": True,
        "complete_topic_fits_heading": True,
        "debate_sections_precise": True,
        "documentation_proportionate_to_literature": True,
        "documentation_family_notes": {
            "bibliography": "Broad syntheses and foundational works were reviewed separately.",
            "webliography": "Substantive web resources were retained only for distinct value.",
            "videography": "Audiovisual coverage was examined and justified independently.",
        },
        "subsections": [
            {
                "title": "Definition",
                "purpose": "Define the subject.",
                "necessary_for_understanding": True,
                "technical_or_specialized": False,
                "relevance_to_debate_explained": True,
            }
        ],
    }
    return {
        "normative_revision": "1.2.7",
        "entries": [dict(base, language="fr"), dict(base, language="en")],
    }


def test_norm_127_introduction_review_requires_precision_and_documentary_notes():
    actual = {"fr": ["Definition"], "en": ["Definition"]}
    review = _intro_review()
    initial = validate_introduction_review_data(review, actual, norm="1.2.7")
    assert not any(i["reason"] in {"debate_sections_precise", "documentation_family_note", "documentation_family_notes", "documentation_proportionate_to_literature"} for i in initial)
    review["entries"][0]["debate_sections_precise"] = False
    review["entries"][1]["documentation_family_notes"]["videography"] = "Too short"
    reasons = {i["reason"] for i in validate_introduction_review_data(review, actual, norm="1.2.7")}
    assert "debate_sections_precise" in reasons
    assert "documentation_family_note" in reasons


def test_norm_127_forceful_expression_must_occur_in_summary():
    nodes = [{"id": "A0001"}]
    pages = {"A0001": {"fr"}}
    summary = "Un résultat inhabituel ne porte pas en lui l'étiquette de sa cause. Il faut encore établir un mécanisme fiable."
    review = {
        "normative_revision": "1.2.7",
        "entries": [
            {
                "id": "A0001",
                "languages": {
                    "fr": {
                        "status": "revised",
                        "thesis_first": True,
                        "general_public_style": True,
                        "sentence_rhythm_reviewed": True,
                        "technical_terms_reviewed": True,
                        "opening_develops_title": True,
                        "example_or_data_reviewed": True,
                        "assertive_tone_reviewed": True,
                        "no_artificial_example_or_number": True,
                        "no_polemical_overstatement": True,
                        "conviction_visible": True,
                        "forceful_expression": "ne porte pas en lui l'étiquette de sa cause",
                        "note": "Expression ferme repérée directement dans le résumé français.",
                    }
                },
            }
        ],
    }
    decision, summary = complete_summary_decision(review["entries"][0]["languages"]["fr"], summary=summary)
    decision["mechanism_statement"] = "Il faut encore établir un mécanisme fiable."
    review["entries"][0]["languages"]["fr"] = decision
    assert validate_summary_style_review_data(review, nodes, pages, norm="1.2.7", summaries={("A0001", "fr"): summary}) == []
    review["entries"][0]["languages"]["fr"]["forceful_expression"] = "une formule absente du résumé"
    reasons = {i["reason"] for i in validate_summary_style_review_data(review, nodes, pages, norm="1.2.7", summaries={("A0001", "fr"): summary})}
    assert "forceful_expression_not_in_summary" in reasons
